### ISSUE TITLE
USB Audio: Xonar U7 MKII needs `iec958_device` entry

### ISSUE THREAD

**Issue by ndl** [alsa-project/alsa-lib#100]
`USB-Audio.conf` includes V1 of Asus Xonar U7 card but not [MKII version](https://www.asus.com/ch-en/Sound-Cards/Xonar-U7-MKII/), the section `USB-Audio.pcm.iec958_device` should be extended to include the string

        "Xonar U7 MKII" 1

without this S/PDIF output doesn't work.

**Comment by perexg** [comment]
Fixed in 93752fb4de397554e92a4eb9079f77dabaec7d7f . Thank you.
