### ISSUE TITLE
build fails using -flto=auto

### ISSUE THREAD

**Issue by shoober420** [alsa-project/alsa-lib#110]
When compiling alsa-lib with -flto=auto, the build will fail. Here are the logs.

64bit:
[alsa-lib-git-1.2.4-1-x86_64-build.log](https://github.com/alsa-project/alsa-lib/files/5779850/alsa-lib-git-1.2.4-1-x86_64-build.log)

32bit:
[lib32-alsa-lib-minimal-git-1.2.4-1-x86_64-build.log](https://github.com/alsa-project/alsa-lib/files/5779853/lib32-alsa-lib-minimal-git-1.2.4-1-x86_64-build.log)

64bit --with-versioned:
[alsa-lib-git-1.2.4-1-x86_64-build.log](https://github.com/alsa-project/alsa-lib/files/5779857/alsa-lib-git-1.2.4-1-x86_64-build.log)

**Comment by perexg** [comment]
Look to the gitcompile script for the LTO setup for alsa-lib (-flto -flto-partition=none). Other combinations are not supported.
