### ISSUE TITLE
Sound stutters with TC-Helicon GoXLR

### ISSUE THREAD

**Issue by Toniob** [alsa-project/alsa-lib#113]
Hi,

I bought a hardware mixer from TC-Helicon. I mainly use it under windows for streaming. But now, I'm trying to make it work under Linux, which I use for work. The hardware is seen as a multi-inputs multi-outputs soundcard under Linux. I use Debian unstable, Gnome (xwayland) and pulseaudio. It's an usb connected hardware (with its own power).

The sound was stuttering every 3 or 4 seconds. It was plugged on a usb 3.0 port on the motherboard. But then, I bought a pci-express usb 3.0 card and I plugged the goxlr on it. The stutters are steal present but less often (I'd say on every 30 seconds).

I've opened an issue on pulseaudio gitlab but it doesn't seem related to pulse as I've got the issue with alsa only : https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1093 .

I know a person, met on the discord of tc-helicon, who has exactly the same symptoms with another distribution.

Another fun fact is that the inputs do not stutter. I can record my mic plugged in the goxlr and it never stutters.

**Comment by perexg** [comment]
This issue seems not related to alsa-lib.  Please, report the kernel driver issues at https://bugzilla.kernel.org. Also note that there are many recent USB driver fixes, so you may test the latest (vanilla) kernel. @tiwai - FYI.
