### ISSUE TITLE
sof topology compilation fails

### ISSUE THREAD

**Issue by juimonen** [alsa-project/alsa-lib#114]
sof topologies fail to compile because of following commit:

commit 51e1d486ce4535923692bd1d7e59d5aa3a29cd50
Author: Jaroslav Kysela <perex@perex.cz>
Date:   Thu Jan 7 17:40:42 2021 +0100

    topology: parse_tuple_set() - remove dead condition code

    Signed-off-by: Jaroslav Kysela <perex@perex.cz>

I don't completely understand the change...? we are in "case SND_SOC_TPLG_TUPLE_TYPE_WORD" and then we check for SND_SOC_TPLG_TUPLE_TYPE_WORD (and not the value anymore) and error out?

**Comment by juimonen** [comment]
@perexg FYI

**Comment by perexg** [comment]
Yes, my fault. The fix is above. Thank you for your report.
