### ISSUE TITLE
[Regression] Game "Rise of the Tomb Raider" crashes at launch

### ISSUE THREAD

**Issue by Oschowa** [alsa-project/alsa-lib#116]
The the native linux version of the game "Rise of the Tomb Raider" crashes at launch when it doesn't detect a working pulseaudio server and it falls back to alsa-lib directly. This is a regression, the last working alsa-lib version is v1.2.1.2 and bisection yields 5ee5ef31b5ff3f as the first bad commit. The crash happens when using "real" alsa hardware drivers as well as when running on the pulseaudio-alsa or pipewire-alsa software plug. Happy to provide more info if i can.

**Comment by perexg** [comment]
This is not an alsa-lib bug. We cannot fix the broken caller code. Use a workaround described in:

https://github.com/alsa-project/alsa-lib/issues/38
https://github.com/alsa-project/alsa-lib/issues/27
