### ISSUE TITLE
yoga 9i bottom speakers do not work

### ISSUE THREAD

**Issue by zany130** [alsa-project/alsa-lib#120]
this might be the same issue as the c940 and legion 7i not sure, but the soundbar works but the bottom speakers don't

https://linux-hardware.org/?probe=1f0bdc3a66

I was trying to get the ALSA Information Script running and the script uploaded but it wasn't connecting so here is the file
[alsa-info.txt](https://github.com/alsa-project/alsa-lib/files/6026794/alsa-info.txt)

**Comment by perexg** [comment]
Apparently, it's a kernel driver bug. Please, report it to https://bugzilla.kernel.org .
