### ISSUE TITLE
Front headphones jack not reporting state to Pulseaudio correctly (always unplugged)

### ISSUE THREAD

**Issue by jose1711** [alsa-project/alsa-lib#130]
ALSA seems to always report state of front headphones jack as "unplugged" to PulseAudio (related bug report: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1180).

[alsa-info.txt](https://github.com/alsa-project/alsa-lib/files/6255379/alsa-info.txt)

**Comment by perexg** [comment]
The kernel issues should be reported to https://bugzilla.kernel.org .
