### ISSUE TITLE
wrong alsa time fix

### ISSUE THREAD

**Issue by circinusX1** [alsa-project/alsa-lib#132]
@@ -42,7 +42,7 @@ long long timestamp2ns(snd_htimestamp_t t)
 {
        long long nsec;
 
-       nsec = t.tv_sec * 1000000000;
+       nsec = (long long)t.tv_sec * 1000000000;
        nsec += t.tv_nsec;

**Comment by perexg** [comment]
Fixed in c71bb0fb39e47381caf49c50615da6bd5fcde619 . Thank you.
