### ISSUE TITLE
1.2.5?

### ISSUE THREAD

**Issue by kloczek** [alsa-project/alsa-lib#140]
Looks like 1.2.5 has been released but I don't see related changes and git tags not only here but in other alsa git repos as well.

**Comment by perexg** [comment]
Sorry, the reltest branch is release testing. I've not announced the release nor tags until my tests are finished.

**Comment by kloczek** [comment]
Funny .. in Fedoa are alredy all alsa* 1.2.5 packages and that cunfuset me a bit :)
I'v been only thinking that you forgot to push your local repo changes to github :)

Closing

**Comment by perexg** [comment]
Yes, Fedora rawhide updates are part of my tests.

**Comment by kloczek** [comment]
So why would you not version that like for example 1.2.4.99?

**Comment by perexg** [comment]
It's very unlikely that the packages will change when they're built. I don't think that this extra step is necessary.
