### ISSUE TITLE
Undefined symbol in static library

### ISSUE THREAD

**Issue by jpalus** [alsa-project/alsa-lib#157]
There is a mismatch between declaration:
https://github.com/alsa-project/alsa-lib/blob/f4c061f349188c548497607efd4622c6e6a43270/src/control/control_symbols.c#L24
and actual definition:
https://github.com/alsa-project/alsa-lib/blob/f4c061f349188c548497607efd4622c6e6a43270/src/control/control_empty.c#L33
resulting in undefined symbol in static library. Judging by convention used in other files I suppose the latter should be renamed to match declaration.

**Comment by perexg** [comment]
Thank you for you report. Your fix seems correct.
