### ISSUE TITLE
Lenovo Legion ALC287/ALC3306 issue

### ISSUE THREAD

**Issue by camberkenpas** [alsa-project/alsa-lib#160]
Hello,

I was able to do a little digging into this issue by running a Windows 10 virtual machine and passing the sound card device to the virtual machine I was able to get audio to play through the laptop's virtual machine using the virtual machine. More importantly, I was able to capture traces that might help us determine what this sound card needs.

I've attached traces at the ticket for this bug:
https://bugzilla.kernel.org/show_bug.cgi?id=208555

Perhaps this is enough to deduce at least some of what verbs the codec wants in order to work.

Is this the right place to share this? Or is the kernel bug tracker the only appropriate place for this?

**Comment by perexg** [comment]
The kernel tracker is the right place for this issue. This tracker is only for the alsa-lib library.
