### ISSUE TITLE
How can turn on auto-mute mode in alsa ?

### ISSUE THREAD

**Issue by yufeiluo** [alsa-project/alsa-lib#164]
My alsa-utils version:

    aplay --version
    aplay: version 1.1.8 by Jaroslav Kysela <perex@perex.cz>

No auto-mute option in alsamixer gui menu.
[https://www.dropbox.com/s/ie6meqto1t1rv9g/alsamixer.png?dl=0](url)

    debian@debian:~$ amixer -c 0 sset 'Auto-Mute Mode' Enabled
    amixer: Unable to find simple control 'Auto-Mute Mode',0

**Comment by perexg** [comment]
It's not available for all hw/drivers.
