### ISSUE TITLE
ASRock (A320M-HDV R4.0) No analog audio driver detected - 

### ISSUE THREAD

**Issue by PedePanoOriginal** [alsa-project/alsa-lib#165]
Hello guys!
I just got a new PC and I was so happy about it. It's a Ryzen 5 - 3600, GeForce GT 1030 GPU, the motherboard is a ASRock A320M-HDV R4.0. The first thing I did when I pluged it in was installing Pop!_OS 20.04 LTS. Everything worked fine except my audio analog ports. They are simply not detected by OS, the only output audio device detected is "GP108 High Definition Audio Controller Digital Stereo".
I've done a lot of googling, tried everything I could find, but, no success. I noticed that when I turn on the PC a message is displayed, something like that: "snd_hda_intel 0000:23:00.4: no codecs found". This message disappear if I turn off onboard audio stuff at the bios.
I would love some help if possible. I'm a linux noob, so I'm sorry to not be able to provide better information now but, I can do it later with some help.

**Comment by perexg** [comment]
It looks like a kernel driver issue. Please, create a new bug at https://bugzilla.kernel.org - audio component.
