### ISSUE TITLE
Error in recording and playing at the same time on raspberry pi

### ISSUE THREAD

**Issue by amirush786** [alsa-project/alsa-lib#174]
I am try to record and play at the same time. I have a speaker connected to pi via aux cable. I have to play a sound from the speaker and also re ord it at the same time from the tool which is seeed microphone tool which is connected to pi. 
I am able to do that but the recorded file has some hissssshhhhhhhh sound in it don't know why it's coming out to that way. But when I do a individual record I can hear a bit proper noise and less of hisshy noise in it. 
And also how can I check the capture sound is high or not. I followed the approach below.
 I did Alsamixer command and it's shows me this.
So after that I typed in F6 to change my card to seeed card.
Then is scroll down to seed card and hit enter. So I see this.
Then I press f4 and I see this so I don't know where should I see that capture is high.
This is the last thing that messing with me.

![20210822_200619.jpg](https://user-images.githubusercontent.com/31735000/131046816-b77895b8-f6c8-4faa-b624-283100ad00f8.jpg)

![20210822_200626.jpg](https://user-images.githubusercontent.com/31735000/131046829-fab9edb3-d9b2-4938-be84-e7dcccfb4aaf.jpg)

![20210822_200641.jpg](https://user-images.githubusercontent.com/31735000/131046851-631a8e34-33f3-4e88-b971-726b2fdd7756.jpg)

**Comment by perexg** [comment]
Please, consult this with the authors of the driver you are using.
