### ISSUE TITLE
alsa-lib 1.2.5 and 1.2.5.1 fail to build with --enable-static

### ISSUE THREAD

**Issue by pjbroad** [alsa-project/alsa-lib#177]
This build successfully:
`./configure  && make clean && make`

This fails to build:
`./configure --enable-shared=no --enable-static=yes && make clean && make`

```
make[1]: Entering directory '/home/paul/el/el-build-scripts/linux-static/libs/alsa-lib-1.2.5.1/aserver'
  CC       aserver.o
  CCLD     aserver
/usr/bin/ld: ../src/.libs/libasound.a(control_symbols.o):(.data.rel+0x8): undefined reference to `_snd_module_control_empty'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:398: aserver] Error 1
make[1]: Leaving directory '/home/paul/el/el-build-scripts/linux-static/libs/alsa-lib-1.2.5.1/aserver'
make: *** [Makefile:405: all-recursive] Error 1
```
`gcc (Ubuntu 11.2.0-3ubuntu1) 11.2.0`

Building static worked find for 1.2.4.  Hopefully someone can help resolve this.  Let me know if you want me to try anything.

**Comment by perexg** [comment]
Already fixed in https://github.com/alsa-project/alsa-lib/commit/81e7923fbfad45b2f353a4d6e3053af51f5f7d0b .
