### ISSUE TITLE
Hint: You are currently not seeing messages from other users and the system. 

### ISSUE THREAD

**Issue by MrRobotAlex** [alsa-project/alsa-lib#183]
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
░░ 
░░ The job identifier is 229.
Oct 09 04:36:11 kali sudo[1169]:     alex : TTY=pts/0 ; PWD=/home/alex ; USER=root ; COMMAND=/usr/bin/su
Oct 09 04:36:11 kali sudo[1169]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 04:39:52 kali sudo[1586]:     alex : TTY=pts/1 ; PWD=/home/alex ; USER=root ; COMMAND=/usr/bin/su
Oct 09 04:39:52 kali sudo[1586]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 04:40:33 kali sudo[1169]: pam_unix(sudo:session): session closed for user root
Oct 09 04:42:07 kali dbus-daemon[772]: [session uid=1000 pid=772] Activating service name='org.freedesktop.thumbnails.Thumbnailer1' requested by ':1>
Oct 09 04:42:07 kali org.freedesktop.thumbnails.Thumbnailer1[1673]: Registered thumbnailer /usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
Oct 09 04:42:07 kali org.freedesktop.thumbnails.Thumbnailer1[1673]: Registered thumbnailer /usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
Oct 09 04:42:07 kali org.freedesktop.thumbnails.Thumbnailer1[1673]: Registered thumbnailer atril-thumbnailer -s %s %u %o
Oct 09 04:42:07 kali dbus-daemon[772]: [session uid=1000 pid=772] Successfully activated service 'org.freedesktop.thumbnails.Thumbnailer1'
Oct 09 04:43:07 kali dbus-daemon[772]: [session uid=1000 pid=772] Activating service name='org.freedesktop.secrets' requested by ':1.57' (uid=1000 p>
Oct 09 04:43:07 kali gnome-keyring-daemon[1939]: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
Oct 09 04:43:07 kali gnome-keyring-d[1939]: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
Oct 09 04:43:08 kali dbus-daemon[772]: [session uid=1000 pid=772] Successfully activated service 'org.freedesktop.secrets'
Oct 09 04:43:12 kali pulseaudio[770]: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Oct 09 04:43:12 kali pulseaudio[770]: Most likely this is a bug in the ALSA driver 'snd_intel8x0'. Please report this issue to the ALSA developers.
Oct 09 04:43:12 kali pulseaudio[770]: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_av>
Oct 09 04:47:10 kali sudo[1586]: pam_unix(sudo:session): session closed for user root
Oct 09 04:48:53 kali sudo[2710]:     alex : TTY=pts/0 ; PWD=/home/alex ; USER=root ; COMMAND=/usr/bin/su
Oct 09 04:48:53 kali sudo[2710]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 04:54:35 kali sudo[2710]: pam_unix(sudo:session): session closed for user root
Oct 09 04:56:20 kali sudo[3350]:     alex : TTY=pts/2 ; PWD=/home/alex/Phisher ; USER=root ; COMMAND=/usr/bin/apt install php libapache2-mod-php
Oct 09 04:56:20 kali sudo[3350]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 04:56:22 kali sudo[3350]: pam_unix(sudo:session): session closed for user root
Oct 09 04:56:37 kali sudo[3358]:     alex : TTY=pts/2 ; PWD=/home/alex/Phisher ; USER=root ; COMMAND=/usr/bin/systemctl restart apache2
Oct 09 04:56:37 kali sudo[3358]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 04:56:37 kali sudo[3358]: pam_unix(sudo:session): session closed for user root
Oct 09 04:56:45 kali sudo[3364]:     alex : TTY=pts/2 ; PWD=/home/alex/Phisher ; USER=root ; COMMAND=/usr/bin/su
Oct 09 04:56:45 kali sudo[3364]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 05:09:13 kali sudo[3364]: pam_unix(sudo:session): session closed for user root
Oct 09 05:09:25 kali sudo[4548]: pam_unix(sudo:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=alex rhost=  user=alex
Oct 09 05:09:31 kali sudo[4548]:     alex : TTY=pts/0 ; PWD=/home/alex ; USER=root ; COMMAND=/usr/bin/su
Oct 09 05:09:31 kali sudo[4548]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 09 05:09:39 kali sudo[4548]: pam_unix(sudo:session): session closed for user root
lines 3058-3093/3093 (END)

**Comment by perexg** [comment]
Dup of #90 .
