### ISSUE TITLE
Tenacity throws error when running "build/bin/Debug/tenacity" to run it

### ISSUE THREAD

**Issue by User10987654321** [alsa-project/alsa-lib#184]
context: https://github.com/tenacityteam/tenacity/issues/649

`cat /proc/asound/version` output: Advanced Linux Sound Architecture Driver Version k5.10.0-kali9-amd64

backtrace, which is only produced in a popup once I comment out the lines "pcm.rear #cards.pcm.rear 
pcm.center_lfe #cards.pcm.center_lfe
pcm.side #cards.pcm.side", which produce the following backtrace in a popup labeled "../src/AudioIOBase.cpp(501): assert "false" failed in getRecordDevIndex():":

ASSERT INFO:
../src/AudioIOBase.cpp(501): assert "false" failed in getRecordDevIndex().

BACKTRACE:
[1] AudioIOBase::getRecordDevIndex(wxString const&)
[2] AudioIO::Init()
[3] AudacityApp::InitPart2()
[4] AudacityApp::OnInit()
[5] wxAppConsoleBase::CallOnInit()
[6] wxEntry(int&, wchar_t**)
[7] wxEntry(int&, char**)
[8] main
[9] __libc_start_main
[10] _sta

When going through the steps in https://github.com/tenacityteam/tenacity/blob/master/BUILDING.md, I eventually get to a point where I run the command in the issue title which brings up the tenacity logo on screen and then provides the following errors in the terminal:

ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:835:(_snd_pcm_a52_open) a52 is only for playback
zsh: segmentation fault  ./tenacity/build/bin/Debug/tenacity

How can I mitigate this to use tenacity successfully?

**Comment by geraldog** [comment]
In my humble opinion Tenacity is segfaulting when it doesn't find a recording device.

Very ungraceful but hardly related to ALSA.

**Comment by User10987654321** [comment]
> In my humble opinion Tenacity is segfaulting when it doesn't find a recording device.
> 
> Very ungraceful but hardly related to ALSA.


This issue still hasn't been solved and I have yet to figure out what's causing it. I have a microphone that's running successfully according to pulseaudio volume control, yet when turned on, it provides the same, slightly altered output all in text in the terminal after a second-long tenacity logo popup:

ALSA lib pcm_dsnoop.c:600:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:835:(_snd_pcm_a52_open) a52 is only for playback
zsh: segmentation fault  build/bin/Debug/tenacity

**Comment by User10987654321** [comment]
> In my humble opinion Tenacity is segfaulting when it doesn't find a recording device.
> 
> Very ungraceful but hardly related to ALSA.

If it's mostly unrelated to alsa, where could I turn to to find  a solution to this fairly enormous problem?

**Comment by Be-ing** [comment]
> context: tenacityteam/tenacity#649

That is a completely different backtrace. This looks like a bug in Tenacity, not ALSA.

**Comment by User10987654321** [comment]
> I'll rephrase my previous statement:
> 
>     1. Tenacity doesn't find a recording device
> 
>     2. It defaults to a52 as a recording device
> 
>     3. a52 only handles playback. Segfault
> 
> 
> That's what I think is happening @User10987654321
> 
> What kind of sound hardware are you trying to use with Tenacity?
> 
> Does the arecord program from alsa-utils work with your mic?

`when I run arecord -d 5 -f U8 sample.mp3` and then `aplay sample.mp3`, I get audio output, I believe this means it works with my microphone.

Do any of you have a solution in mind, or should I look to tenacity issues or somewhere else?

**Comment by geraldog** [comment]
@User10987654321 thanks, you may be able to get away with running Tenacity by editing ~/.asoundrc

See https://wiki.audacityteam.org/wiki/USB_mic_on_Linux#Setting_default_recording_device

**Comment by User10987654321** [comment]
> @User10987654321 thanks, you may be able to get away with running Tenacity by editing ~/.asoundrc
> 
> See https://wiki.audacityteam.org/wiki/USB_mic_on_Linux#Setting_default_recording_device
> 
> Please note that the above mentioned link is meant only as an example and that you might have to adapt it.

Hello, I tried adding the ~/.asoundrc with the text inside it but, as implied above, it's difficult to find how it can be adapted to my system. 
How might I find out the specifics of configuring the ~/.asoundrc file correctly so I can get closer to successfully running tenacity?

**Comment by User10987654321** [comment]
> Please bear in mind that this configuration is very much untested and based on the parameters you provided.
> 
> > pcm.!default {
> > ```
> >    type asym
> >    playback.pcm {
> >            type plug
> >            slave {
> >                    pcm "hw:0,0"
> >                    rate 48000
> >            }
> >    }
> >    capture.pcm {
> >    type plug
> >            slave {
> >                    pcm "hw:5,0"
> >                    format U8
> >                    rate 48000
> >            }
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }

Okay, when I used the one you created instead of the link's, I at least got a backtrace instead of an instant crash. I'll continue to look into getting tenacity up and running.

**Comment by User10987654321** [comment]
Hello, I just ran `arecord -d 5 -f S16_LE -c2 -r48000 sample.mp3` and then `aplay sample.mp3' and got clear audio back, but after using tenacity(since the interface was working, just without any audio) and turning off some popups, the .asoundrc file you sent is no longer working and providing the same terminal error output as in the original post.

If you'd like the audio specifications, specific commands to find each one could be useful and maybe even provide information necessary to a solution.

**Comment by geraldog** [comment]
@User10987654321 try to delete the contents of directory ~/.config/tenacity like I mentioned before.

Also note that if your system runs PulseAudio, you need to either stop or suspend it temporarily to be able to use Tenacity directly with ALSA backend. See https://askubuntu.com/questions/8425/how-to-temporarily-disable-pulseaudio-while-running-a-game-under-wine

Here's a revised .asoundrc based on your latest comments:

pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave {
                        pcm "hw:0,0"
                        format S16_LE
                        rate 48000
                }
        }
        capture.pcm {
        type plug
                slave {
                        pcm "hw:5,0"
                        format S16_LE
                        rate 48000
                }
        }
}

**Comment by geraldog** [comment]
@User10987654321 maybe there is already a pcm default definition in your /etc/asound.conf ?

Also, try to set PortAudio environment variables, e.g.:

set PA_RECOMMENDED_OUTPUT_DEVICE=0
set PA_RECOMMENDED_INPUT_DEVICE=0

This should use pcm default I think, but you may try variations if it doesn't work, with and without an .asoundrc

**Comment by User10987654321** [comment]
> You're either missing PortAudio or it is installed in a non-standard location and in a non-standard way such that CMake is unable to find it.
> 
> Fix the PortAudio issue, and re-run CMake configure phase. Preferrably delete directory `build` prior to reconfiguration.

It successfully built with `cmake -G Ninja -S . -B build` after installing libportaudio-ocmal-dev.
I'm completing the build process now as it runs `camke --build build` while I type.

**Comment by geraldog** [comment]
@User10987654321 try compiling https://raw.githubusercontent.com/EddieRingle/portaudio/master/examples/pa_devs.c with `gcc -o pa_devs pa_devs.c -lportaudio` because ALSA default pcm on my system for example is device 8.

So you would delete the contents of ~/.config/tenacity, make sure you have the right configuration in .asoundrc and that asound.conf is not conflicting with that, then set environment variable for PortAudio:

set PA_RECOMMENDED_OUTPUT_DEVICE=8
set PA_RECOMMENDED_INPUT_DEVICE=8

varying with the output of ./pa_devs

All this before actually trying to run Tenacity.

**Comment by geraldog** [comment]
@User10987654321 OK, try:

set PA_RECOMMENDED_OUTPUT_DEVICE=23
set PA_RECOMMENDED_INPUT_DEVICE=23

Also, I don't think you had your mic connected when you ran pa_devs. Is it a USB mic?

**Comment by User10987654321** [comment]
@geraldog 
bluetooth, WH-1000XM4

**Comment by User10987654321** [comment]
@geraldog
just tried with 

> @User10987654321 OK, try:
> 
> set PA_RECOMMENDED_OUTPUT_DEVICE=23 set PA_RECOMMENDED_INPUT_DEVICE=23
> 
> Also, I don't think you had your mic connected when you ran pa_devs. Is it a USB mic?

and got same terminal output from build/bin/Debug/tenacity

**Comment by User10987654321** [comment]
> As far as I know, it will be impossible for you to use a bluetooth-enabled headset with ALSA only.
> 
> This requires either PulseAudio or PipeWire.

Okay, so will it be impossible for me to use tenacity with a bluetooth headset?

**Comment by User10987654321** [comment]
@geraldog 
I have a usb headset I could use with it, but if I could somehow use pulseaudio with everything, that would be of incredible convenience.

**Comment by User10987654321** [comment]
> @User10987654321 the problem is the segfault
> 
> Probably one of my last tries at helping you, but do `apt remove libasound2-plugins` and try to run Tenacity.

just ran `sudo apt remove libasound2-plugins` then `~/tenacity/build/bin/Debug/tenacity` and the gui appears to be running flawlessly at immediate bootup.

**Comment by geraldog** [comment]
Cool, but you need that package. You need to apt install it back again
