### ISSUE TITLE
When will we have a new release?

### ISSUE THREAD

**Issue by leiserfg** [alsa-project/alsa-lib#185]
There was an issue in the last release that affects pipewire while using laptops with `Comet Lake PCH` that was solved in alsa after the release. I'm  currently using `master` via AUR but will love to be able to use a release version (so I don't have to re-build with every change on master)

**Comment by perexg** [comment]
Most probably this month. Distributions usually pick the fixes faster.

**Comment by joakim-tjernlund** [comment]
December, must be close now?
I got a SOF related bug I want to see if it still there with new ALSA

**Comment by perexg** [comment]
I'll start release tests on next Monday. I apologize, but some other things were in the queue.

**Comment by perexg** [comment]
Done. 1.2.6 is out.
