### ISSUE TITLE
Where did snd_pcm_parse_control_id() go?

### ISSUE THREAD

**Issue by Saur2000** [alsa-project/alsa-lib#186]
It seems `snd_pcm_parse_control_id()` was made private in 1.2.5 without any prior deprecation. It is still present in `pcm_external.h`, and our code now fails to link with:

```
ld: src/plugin_control.o: in function `plugin_control_load_user_control':
src/plugin_control.c:254: undefined reference to `snd_pcm_parse_control_id'
```

What are we supposed to use instead?
And why is the function still in the header file if it is not in the library?

**Comment by perexg** [comment]
I added the code back (will be in 1.2.6) with the deprecated attribute in f0d540f851de3992a5e285dcea0be7cab293527e . Anyway, I suggest to copy the code to the caller. Called functions (from `snd_pcm_parse_control_id()` are available).
