### ISSUE TITLE
Unable to connect KEF X300A USB speakers

### ISSUE THREAD

**Issue by simbatl** [alsa-project/alsa-lib#189]
I'm trying to use a pair of KEF X300A speakers. They work with aplay on Ubuntu 20.04 server, but fail on Ubuntu 18.04, 20.04 and 21.10 desktop.

Here is output from pulseaudio -vvv:
[pulse.log](https://github.com/alsa-project/alsa-lib/files/7527770/pulse.log)

And here is output from alsa-info.sh:
[alsa-info.txt](https://github.com/alsa-project/alsa-lib/files/7527773/alsa-info.txt)

Anyone who know how to solve this issue? :)

**Comment by perexg** [comment]
It looks like a general USB issue. Check your kernel logs.

**Comment by simbatl** [comment]
It works on windows 10 and ubuntu 20.04 server without any problems, so think usb connection is ok.

Here is output from dmesg:
[dmesg.log](https://github.com/alsa-project/alsa-lib/files/7528033/dmesg.log)

**Comment by perexg** [comment]
There are a log of errors for `usb-1.8` bus. It may be a problem somewhere in hardware or kernel or a timing issue (which is a bit problematic to debug). You may check the kernel version and report the issue at https://bugzilla.kernel.org or better using the distribution specific reporting system (all distributions modifies kernels a bit). They'll work with you to resolve this issue.

**Comment by simbatl** [comment]
Ok, thanks! :)

**Comment by perexg** [comment]
Also, it may be worth to try to connect PC and speakers to one phase (one socket).

**Comment by simbatl** [comment]
They already are, and the speakers works on the same usb port if I pass it to windows 10 with virtualbox. :o
