### ISSUE TITLE
HP Probook Mute volume + mic LED indicators not working (Audio codec = ALC236)

### ISSUE THREAD

**Issue by antintin0** [alsa-project/alsa-lib#190]
Tested on kernel 5.13 and 5.15.2
Not sure if this is the right place to ask, but no one else seems to be able to help.
I have an HP Probook x360 435 g7 with the Realtek ALC236 codec and my mute volume + mute mic LED indicators aren't working (they do on windows). I found there were some patches mentioning mute LEDs on ALC236 on the below links:
https://patchwork.kernel.org/project/alsa-devel/patch/20210701091417.9696-1-andy.chi@canonical.com/
https://mailman.alsa-project.org/pipermail/alsa-devel/2021-November/192225.html

But obviously they're not working for me, so I tried following this: https://wiki.archlinux.org/title/Laptop#Audio_mute_LED
Theres nothing specific for ALC236 but I tried pretty much all the relevant parameters for the snd-hda-intel module option "model" under "ALC22x/23x/25x/269/27x/28x/29x (and vendor-specific ALC3xxx models)" and none worked.

Any help would be appreciated

**Comment by perexg** [comment]
It's a kernel issue. Please, create a bug in https://bugzilla.kernel.org - Audio component.
