### ISSUE TITLE
GIT Project URLS

### ISSUE THREAD

**Issue by h1z1** [alsa-project/alsa-lib#196]
Hi

Not really sure where to report this, are the URLS listed on alsa-project.org accurate?   They include GIT and  HTTP, not HTTPS and are not correct regardless.

ex (from https://alsa-project.org/wiki/GIT_Server)

```
Web interface

          http://git.alsa-project.org/?p=alsa-driver.git
```

Results in what I"m assuming is a 404

```
$ git clone https://git.alsa-project.org/?p=alsa-driver.git alsa-driver.git
Cloning into 'alsa-driver.git'...
fatal: repository 'https://git.alsa-project.org/?p=alsa-driver.git/' not found
```

Worth noting gitweb is reachable.

Should those URLs be accessible via HTTPS?

**Comment by perexg** [comment]
The page referred to some old repos which are no longer used. I tried to fix it. Let me know, if you find something else. Thank you.
