### ISSUE TITLE
alsa crashing each time my screen gets locked

### ISSUE THREAD

**Issue by Fallast** [alsa-project/alsa-lib#203]
each time i get my screen lock after being inactive for 5 minutes i log back in and alsa stops working and my volume icon disappears
i have to run volumeicon to get it working back again
i'm on mx linux, based on debian bullseye

**Comment by perexg** [comment]
Could you show output (attach or post a gist/pastebin URL) to the `alsa-info.sh --no-upload` output before and after suspend (don't run volumeicon).

**Comment by Fallast** [comment]
https://pastebin.com/UXKX6cz7 (before)
https://pastebin.com/zefXjNeQ (after)

**Comment by perexg** [comment]
Thank you. I don't see any problem here. It may be related to your GUI environment or pulseaudio or so...

Does speaker-test work for you? `pasuspender -- speaker-test -D plughw:0` before and after (from command line)?

**Comment by Fallast** [comment]
thanks for your quick reply, and yes pasuspender -- speaker-test -D plughw:0 does work before and after! so i guess it must be something else
