### ISSUE TITLE
Does alsa-lib call this kernel api?

### ISSUE THREAD

**Issue by Nick0412** [alsa-project/alsa-lib#204]
Where in the alsa library does it reference the alsa kernel api: https://www.kernel.org/doc/html/latest/sound/kernel-api/alsa-driver-api.html?

Do these two apis interact at all?

**Comment by Nick0412** [comment]
I should add, where are the system calls made in alsa-lib that call the kernel alsa api?

**Comment by perexg** [comment]
The user space <-> kernel communication is using the character devices (open/close/ioctl/read/write).
