### ISSUE TITLE
ALSA update from 1.2.5.1 to 1.2.6.1 loses audio devices on Dell XPS 9700

### ISSUE THREAD

**Issue by roland-d** [alsa-project/alsa-lib#206]
Hello,

On December 16, Manjaro pushed an update which included an ALSA update from 1.2.5.1 to 1.2.6.1. This has caused users of a DELL XPS 9700 to no longer show any audio devices except the built-in speaker. This has been reported in the release post as well by a user named sparcplug.
https://forum.manjaro.org/t/stable-update-2021-12-16-kernels-kde-gear-21-12-0-gnome-extensions-libreoffice/94942/18

I can confirm that for me the audio devices also disappeared. A rollback to 1.2.5.1 and restart of the system brought back the sound devices.

I have no idea what causes this but wanted to report it and if you need me to test I am happy to do so.

**Comment by perexg** [comment]
I believe it's fixed in the recent alsa-ucm-conf update (1.2.6.2 version). Ask your distro to update this package.
