### ISSUE TITLE
Alsa applies noise cancelling when not desired

### ISSUE THREAD

**Issue by Martmists-GH** [alsa-project/alsa-lib#211]
In my [original issue](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1306) on pulseaudio I was told it was an alsa issue.

**Comment by perexg** [comment]
It looks like an ALSA linux kernel driver issue. Please, enter a new bug to https://bugzilla.kernel.org - Audio component - describe the issue again.
