### ISSUE TITLE
HDMI audio broken in 1.2.7 for old laptops

### ISSUE THREAD

**Issue by hwpfeil** [alsa-project/alsa-lib#235]
Tag 1.2.7 breaks HDMI audio on HP laptops with AMD A6-5200 APU (video works). No HDMI option in System Settings|Audio Devices, both KDE and XFCE. Reverting to 1.2.6.1 restores the HDMI Audio Device. There should come a time when such dinosaurs are declared obsolete and no longer supported. They can keep running on 1.2.6.1. Not sure if it needs fixing.

**Comment by perexg** [comment]
Dup of #233.
