### ISSUE TITLE
No sound on AMD audio device

### ISSUE THREAD

**Issue by chvmq** [alsa-project/alsa-lib#241]
I have a laptop huawei 14 amd 2021

I don't know where write about it. maybe there

I tried ubuntu | arch-linux and no sound at all

![image](https://user-images.githubusercontent.com/60788249/174885007-8eb96062-3753-47b6-9880-5a45b57071ac.png)
![image](https://user-images.githubusercontent.com/60788249/174885044-42b8c5c2-6c64-46df-ade6-6f5c8388a972.png)
![image](https://user-images.githubusercontent.com/60788249/174885077-b13fc2a4-18cb-4f20-84a7-3c611ebbecc3.png)

**Comment by perexg** [comment]
The kernel driver related bugs should be reported at https://bugzilla.kernel.org (Audio group).
