### ISSUE TITLE
How to get mixer control index from UCM

### ISSUE THREAD

**Issue by Zames-Chang** [alsa-project/alsa-lib#248]
I use  Corsair VOID ELITE USB Gaming Headset. However this headset have two same name control
```
$ amixer -c 1 scontrols
Simple mixer control 'Auto Gain Control',0
Simple mixer control 'Headset',0
Simple mixer control 'Headset',1
```
use command to change 'Headset',0 is actually not working. But change 'Headset',1 will work. I want write a UCM to indicate that when seeing this headset, choose the name 'Headset' with index 1 not index 0. 

I have seen [use-case.h](https://github.com/alsa-project/alsa-lib/blob/master/include/use-case.h) recommended names for values, but I don't find a proper name to describe control index.

Is there any suggestion about how to write control index in UCM file?

**Comment by perexg** [comment]
```
PlaybackMixerElem "Headset,1"
```

or

```
PlaybackMixerElem "'Headset',1"
```

or

```
PlaybackMixerElem '"Headset",1'
```

**Comment by Zames-Chang** [comment]
Many Thanks
