### ISSUE TITLE
hda_dsp_hdmi_build_controls: no PCM in topology - intel/sof-tplg/sof-hda-generic-2ch.tplg

### ISSUE THREAD

**Issue by Nightwing0815** [alsa-project/alsa-lib#252]
updated:

Hey there,

I've done some research and I hope for a little help now in here:

I'm wondering, why i can't send a pcm signal via HDMI to my TV ( and from there to my Teufel Decoderstation),
i so i looked in here and do some tests: To finally get the topology file, i removed all of them and rebooted, so dmesg can tell me the missing topology, which is: intel/sof-tplg/sof-hda-generic-2ch.tplg

But, the people on sof told me, thats not a sof problem, as you can read here: [https://github.com/thesofproject/linux/issues/4129](https://github.com/thesofproject/linux/issues/4129)

I just did some files with output to upload here, like alsa-info:

[alsa-info.txt](https://github.com/thesofproject/sof-bin/files/10368590/alsa-info.txt)
[alsaucm -c hw:0 dump.txt](https://github.com/thesofproject/sof-bin/files/10368591/alsaucm.-c.hw.0.dump.txt)
[amixer -c 0 scontents.txt](https://github.com/thesofproject/sof-bin/files/10368592/amixer.-c.0.scontents.txt)
[aplay -lL.txt](https://github.com/thesofproject/sof-bin/files/10368593/aplay.-lL.txt)
[arecord -lL.txt](https://github.com/thesofproject/sof-bin/files/10368594/arecord.-lL.txt)
[intel-snd.log](https://github.com/thesofproject/sof-bin/files/10368595/intel-snd.log)
[systemctl --user status pipewire pipewire-session-manager.txt](https://github.com/thesofproject/sof-bin/files/10368596/systemctl.--user.status.pipewire.pipewire-session-manager.txt)
[wpctl status.txt](https://github.com/thesofproject/sof-bin/files/10368597/wpctl.status.txt)

and here inxi with more details from my device: 
[inxi.txt](https://github.com/thesofproject/sof-bin/files/10368609/inxi.txt)

Maybe, we'll find a solution for my system, to get pcm work...

Greetings and thanks in advance,

ToM

**Comment by Nightwing0815** [comment]
update, maybe helpful :-)

**Comment by perexg** [comment]
It does not appear like alsa-lib issue. Please, continue in the SOF project.
