### ISSUE TITLE
snd_soc_skl - No sound on PopOS

### ISSUE THREAD

**Issue by runcros** [alsa-project/alsa-lib#255]
Hello, I have no sound on skylake nau8825 max98357a here is my alsa-info : http://alsa-project.org/db/?f=c1b90f94c1bb072f507636f3979c0bc8a62ae470
Can you help me please
If you need others infos, I am here =) thank you !

**Comment by perexg** [comment]
Please, report this in the kernel bugzilla: https://bugzilla.kernel.org (Audio group). It seems like a driver issue.
