### ISSUE TITLE
Support for "Technics USB Audio" SU-G700M2

### ISSUE THREAD

**Issue by Argo16x** [alsa-project/alsa-lib#256]
In the last years Technics launched on the market a new mid-high end line of integrated amplifiers, one of theese is the SU-G700M2, second revision of the acclaimed SU-G700. The Technics SU-G700M2 has been well accepted by the market due to his reasonable price tag and (almost) exceptional performace. Audiophiles in the world are buying the M2. Theese amplifiers have a dedicated USB digital input capable to manage PCM up to 32 bit 384 KHz and DSD 256-512 either in Native or DOP mode.

This digital USB input is supported officially on Windows only by an ASIO Windows driver made by Technics and it does work, unofficially, with ALSA but on any pre-built product I'ìve tried (Volumio, Moode, rAudio), based on ALSA ,the playback does not work at first try; at startup or at any change of sample rate, it stops with an error and  you have to push play twice (or again) to actually have ALSA sending the data to the device. This is, for an example, what I get using aplay with thie following command line:

>flac -d -c 2L-082_stereo-192kHz_01.flac | aplay --disable-resample -D plughw:1,0 --dump-hw-params

At first try I get:

>aplay: set_params:1454: Unable to install hw params:

If I send the same identical command a second time, no error comes up, I get the "pseudo DAC" parameters and the file actually plays nicely every subsequent file will also play, providing it has the same sample rate of the former.
It seems some sort of timing/protocol problem and I'd really like to resolve it but I'm a total noob regarding Linux programming. This is why I'm writing here.

Of course I'm available to make any neccessary/useful test on my setup (currently rAudio 1 on Raspberry PI 3B+).

Thank you.
Simone

**Comment by perexg** [comment]
The kernel driver bugs should be reported at https://bugzilla.kernel.org (Audio group). Please, attach output from `alsa-info.sh --no-upload` script to your report. Thanks.
