### ISSUE TITLE
snd_pcm_readi(),return -11,Resource temporarily unavailable

### ISSUE THREAD

**Issue by xukawendi** [alsa-project/alsa-lib#259]
i called the function snd_pcm_readi() to capture pcm data, but the function returns -11,and the snd_strerror(-11) shows "Resource temporarily unavailable",How can I resolve this problem?

**Comment by perexg** [comment]
Error -11 is EAGAIN. It's standard linux error code for the non-blocking I/O. See `man 3 read` and look for EAGAIN / O_NONBLOCK comments.
