### ISSUE TITLE
usage of snd_rawmidi_status_get_avail()

### ISSUE THREAD

**Issue by MusicMaker** [alsa-project/alsa-lib#26]
In non blocked raw MIDI, is snd_rawmidi_status_get_avail supposed to return the number of available bytes that can be read using a snd_rawmidi_read. (port is opened for input only)  It seems get_avail always returns 0 even there is MIDI data when using a read.  Else is there a(nother) way to find the number of unread received bytes in the buffer?
snd_rawmidi_status_alloca (&status);  	
snd_rawmidi_status(client, status); 
snd_rawmidi_status_get_avail(status);

**Comment by cladisch** [comment]
`snd_rawmidi_status_get_avail()` indeed should return the number of bytes that can be read.

Please check that `snd_rawmidi_status()` did not return an error.

How do you determine that there is MIDI data? What are the contents of `/proc/asound/cardX/midi0` at that point of time?

**Comment by symdeb** [comment]
It now works, only it seems at least one read must be done to the port, before avail will return values  > 0, otherwise it always will return 0. I used avail before the read and if was zero the port was never read.

**Comment by symdeb** [comment]
So far debugging this, it looks like at least one read to the port must be done before avail will return values > 0.

**Comment by MusicMaker** [comment]
So far debugging this, it looks like at least one read to the port must be done before avail() will return values > 0

**Comment by cladisch** [comment]
Yes, you need to actually read bytes (or poll for them) to trigger the driver to actually read from the hardware.

**Comment by symdeb** [comment]
Ok, Thanks , with that, it works and could get multiple bytes in a red. Closed.

**Comment by MusicMaker** [comment]
Ok, Thanks , with that, it works and could get multiple bytes in a read.
P.S should avail return bytes that can be written to the output buffer (before it is full ) ?

**Comment by cladisch** [comment]
Yes, "available" means bytes that can be read or written.
