### ISSUE TITLE
Most speakers don't work

### ISSUE THREAD

**Issue by JonathanReeve** [alsa-project/alsa-lib#28]
I have a Lenovo Yoga C-930, which has a Dolby sound bar, and it seems that only one or two out of six speakers work. Is there a way I can make this work? 

Here's my alsa-info: http://alsa-project.org/db/?f=87931920f5a8cbfcaa9a2490b88d8c1ed6337e9f

**Comment by perexg** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=205755

Ask Lenovo to add the initialization for all speakers to the BIOS.

**Comment by JonathanReeve** [comment]
Is there another way that we could initialize those amplifiers? I've been in contact with Lenovo several times, and they just turn off completely whenever Linux is mentioned.
