### ISSUE TITLE
alsa-project.org is down

### ISSUE THREAD

**Issue by afq984** [alsa-project/alsa-lib#287]
```
curl -i https://alsa-project.org
HTTP/2 404 
server: nginx/1.14.1
date: Fri, 09 Dec 2022 16:34:22 GMT
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.4.30

No input file specified.
```

**Comment by afq984** [comment]
Thanks for the update. We were using FTP to download the library in our CI and https://alsa-project.org/files/ works for us.

**Comment by perexg** [comment]
Ohh. FTP is back, too.

**Comment by perexg** [comment]
Wiki is live again now. Closing.

**Comment by esramirez** [comment]
The git proxy is not running. Can some one please help?

**Comment by perexg** [comment]
Fixed. Thanks.

**Comment by esramirez** [comment]
Perfect! Thank you

**Comment by forca84** [comment]
https://git.alsa-project.org
down again :(

**Comment by AkraAME** [comment]
Git service is unfortunately down again.

**Comment by perexg** [comment]
Service provider status:

"""
2.09.2024 02:07 pm (UTC+2) Disruption in our Nuremberg Data Center
We regret to inform you that an unexpected cooling issue at our Nuremberg Data Center is affecting several services:

- Some servers may be unreachable.
- Placing new orders is currently not possible.
- Accessing the Customer Control Panel is unavailable.
- Object Storage in the EU may be inaccessible.
- The customer support ticketing system is not functioning.

Our technicians are actively working on resolving these issues, but there is currently no estimated time for resolution. We kindly ask that you refrain from creating new tickets during this time. We apologize for the inconvenience and appreciate your patience.
"""
