### ISSUE TITLE
Issues with Aorus Z490 Extreme

### ISSUE THREAD

**Issue by FlanOfHarmony** [alsa-project/alsa-lib#294]
Hi, I’ve acquired a [Gigabyte Aorus Z490 Extreme](https://www.gigabyte.com/Motherboard/Z490-AORUS-XTREME-rev-1x/sp#sp) motherboard and installed Fedora 37 recently, and I’ve been having some audio issues. This motherboard has two identicals Realtek ALC1220-VB chipsets, one for the front and one for the back. First, I did not find a way to output the sound to the front, which wasn’t too much of a bother.

But then I realized that even at maximum volume the sound is very low, to the point that for some movies I’m having difficulties to hear what’s being said. On the same pc under Windows at 10% volume it’s already louder than on Fedora. On my previous pc the sound under Fedora was way lower than windows at 100% but still more than loud enough, unlike now.

Thirdly, the sound from the microphone input is **extremely** low, even at 100% it is barely possible to hear me. I’ve already used this mic with fedora on my previous computer, and the input sound was more than enough at 50%.

I wanted to open `alsamixer` to check that everything was at 100%, but upon selecting the `HDA Intel PCH` soundcard, the application crashes with `cannot load mixer controls: Invalid argument`. Trying to do the same operation with `qasmixer` seems to give more information : `ALSA lib simple_none.c:1555:(simple_add1) helem (MIXER,'Master Playback Switch',0,1,0) appears twice or more`. The fact that there are two identical ALC1220-VB seems to be causing trouble, and I’m guessing this is what also crashes `alsamixer`.

Here’s the output of `alsa-info.sh`: [alsa-info.txt](https://github.com/alsa-project/alsa-lib/files/10475380/alsa-info.txt)

**Comment by perexg** [comment]
Dup of #205 .
