### ISSUE TITLE
xone mixer

### ISSUE THREAD

**Issue by molli1312** [alsa-project/alsa-lib#303]
Having a few problems with the Xone32c though not sure if this is an ALSA
issue or general USB stack problem.

It's a USB soundcard that is supposed to have 4 inputs and 4 outputs. It
seems to have 2 USB configurations (bNumConfigurations : 0x2). When plugged
in, bConfigurationValue is 0x1 and only 2 inputs and 2 outputs show up.
Change this value to 0x2 and it shows up (as it should) as 4 inputs and 4
outputs.

I can change the bConfigurationValue with this udev rule, or with a `echo 2

/sys/bus/usb/devices/1-1.4/bConfigurationValue`:

This has all been working OK on Ubuntu 20.04 running kernel
5.4.0-33-generic. However, I just updated to 5.4.0-37-generic and now there
is only a single USB configuration (bNumConfigurations : 0x1) and
bConfigurationValue can't be changed to 0x2:

**Comment by perexg** [comment]
This is tracker for the alsa-lib package. The upstream kernel issues are tracked at https://bugzilla.kernel.org (only latest kernels, please). For 5.4.0 - you may discuss your problem with the distribution support. It's really an old kernel.
