### ISSUE TITLE
Most likely this is a bug in the ALSA driver 'snd_hda_intel'

### ISSUE THREAD

**Issue by zozo30** [alsa-project/alsa-lib#310]
márc 31 16:49:45 surface pulseaudio[1449]: snd_pcm_avail() returned a value that is exceptionally large: 153216 bytes (798 ms).
márc 31 16:49:45 surface pulseaudio[1449]: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
márc 31 16:50:09 surface kernel: pulseaudio invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
márc 31 16:50:09 surface kernel: CPU: 6 PID: 1449 Comm: pulseaudio Tainted: G           OE     5.15.0-69-generic #76~20.04.1-Ubuntu
márc 31 16:50:09 surface kernel: Hardware name: Microsoft Corporation Surface Laptop Go/Surface Laptop Go, BIOS 13.102.140 02/04/2022
márc 31 16:50:09 surface kernel: Call Trace:
márc 31 16:50:09 surface kernel:  <TASK>
márc 31 16:50:09 surface kernel:  dump_stack_lvl+0x4a/0x63
márc 31 16:50:09 surface kernel:  dump_stack+0x10/0x16
márc 31 16:50:09 surface kernel:  dump_header+0x53/0x225
márc 31 16:50:09 surface kernel:  oom_kill_process.cold+0xb/0x10
márc 31 16:50:09 surface kernel:  out_of_memory+0x1dc/0x530
márc 31 16:50:09 surface kernel:  __alloc_pages_slowpath.constprop.0+0xd32/0xe30
márc 31 16:50:09 surface kernel:  ? __alloc_pages_slowpath.constprop.0+0xdb6/0xe30
márc 31 16:50:09 surface kernel:  __alloc_pages+0x2cc/0x310
márc 31 16:50:09 surface kernel:  alloc_pages+0x90/0x120
márc 31 16:50:09 surface kernel:  __page_cache_alloc+0x87/0xc0
márc 31 16:50:09 surface kernel:  pagecache_get_page+0x150/0x530
márc 31 16:50:09 surface kernel:  ? page_cache_ra_unbounded+0x16a/0x220
márc 31 16:50:09 surface kernel:  filemap_fault+0x527/0xb60
márc 31 16:50:09 surface kernel:  ? filemap_map_pages+0x138/0x640
márc 31 16:50:09 surface kernel:  __do_fault+0x3d/0x120
márc 31 16:50:09 surface kernel:  do_fault+0x1f9/0x420
márc 31 16:50:09 surface kernel:  __handle_mm_fault+0x62c/0x840
márc 31 16:50:09 surface kernel:  handle_mm_fault+0xd8/0x2c0
márc 31 16:50:09 surface kernel:  do_user_addr_fault+0x1c2/0x660
márc 31 16:50:09 surface kernel:  exc_page_fault+0x77/0x170
márc 31 16:50:09 surface kernel:  asm_exc_page_fault+0x27/0x30
márc 31 16:50:09 surface kernel: RIP: 0033:0x7f2eaaa006e0
márc 31 16:50:09 surface kernel: Code: Unable to access opcode bytes at RIP 0x7f2eaaa006b6.
márc 31 16:50:09 surface kernel: RSP: 002b:00007fff4da75e58 EFLAGS: 00010206
márc 31 16:50:09 surface kernel: RAX: 0000000000000180 RBX: 0000000000000014 RCX: 0000000000007fc8
márc 31 16:50:09 surface kernel: RDX: 0000000000000014 RSI: 00007f2e44007383 RDI: 0000557a946844c8
márc 31 16:50:09 surface kernel: RBP: 0000557a9442fdd0 R08: 00000000000000f6 R09: 00007fff4db96080
márc 31 16:50:09 surface kernel: R10: 0000000000000f60 R11: 0000000000000000 R12: 0000000000000000
márc 31 16:50:09 surface kernel: R13: 0000000000000014 R14: 0000000000000014 R15: 0000557a946844c8
márc 31 16:50:09 surface kernel:  </TASK>
márc 31 16:50:09 surface kernel: Mem-Info:
márc 31 16:50:09 surface kernel: active_anon:434847 inactive_anon:1303910 isolated_anon:0
                                   active_file:274 inactive_file:139 isolated_file:0
                                   unevictable:46304 dirty:0 writeback:0
                                   slab_reclaimable:24619 slab_unreclaimable:38963
                                   mapped:13059 shmem:234049 pagetables:24921 bounce:0
                                   kernel_misc_reclaimable:0
                                   free:25965 free_pcp:2513 free_cma:0
márc 31 16:50:09 surface kernel: Node 0 active_anon:1739388kB inactive_anon:5215640kB active_file:1096kB inactive_file:556kB unevictable:185216kB isolated(anon):0kB isolated(file):0kB mappe>
márc 31 16:50:09 surface kernel: Node 0 DMA free:14340kB min:136kB low:168kB high:200kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictab>
márc 31 16:50:09 surface kernel: lowmem_reserve[]: 0 1777 7398 7398 7398
márc 31 16:50:09 surface kernel: Node 0 DMA32 free:38460kB min:16204kB low:20252kB high:24300kB reserved_highatomic:0KB active_anon:470704kB inactive_anon:1304732kB active_file:120kB inacti>
márc 31 16:50:09 surface kernel: lowmem_reserve[]: 0 0 5621 5621 5621
márc 31 16:50:09 surface kernel: Node 0 Normal free:51060kB min:51240kB low:64048kB high:76856kB reserved_highatomic:2048KB active_anon:1268684kB inactive_anon:3910908kB active_file:1652kB >
márc 31 16:50:09 surface kernel: lowmem_reserve[]: 0 0 0 0 0
márc 31 16:50:09 surface kernel: Node 0 DMA: 1*4kB (U) 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 1*2048kB (M) 3*4096kB (M) = 14340kB
márc 31 16:50:09 surface kernel: Node 0 DMA32: 627*4kB (UME) 351*8kB (UME) 287*16kB (UME) 231*32kB (UME) 89*64kB (UME) 49*128kB (UME) 18*256kB (UME) 8*512kB (ME) 0*1024kB 0*2048kB 0*4096kB >
márc 31 16:50:09 surface kernel: Node 0 Normal: 2543*4kB (UMEH) 2132*8kB (UMEH) 505*16kB (UMEH) 283*32kB (UMEH) 131*64kB (UMEH) 1*128kB (M) 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 5287>
márc 31 16:50:09 surface kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
márc 31 16:50:09 surface kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
márc 31 16:50:09 surface kernel: 248238 total pagecache pages
márc 31 16:50:09 surface kernel: 13889 pages in swap cache
márc 31 16:50:09 surface kernel: Swap cache stats: add 1758716, delete 1745144, find 269293/452373
márc 31 16:50:09 surface kernel: Free swap  = 0kB
márc 31 16:50:09 surface kernel: Total swap = 2097148kB
márc 31 16:50:09 surface kernel: 1991213 pages RAM
márc 31 16:50:09 surface kernel: 0 pages HighMem/MovableOnly
márc 31 16:50:09 surface kernel: 61186 pages reserved
márc 31 16:50:09 surface kernel: 0 pages hwpoisoned

márc 31 16:50:09 surface kernel: Out of memory: Killed process 59760 (Isolated Web Co) total-vm:3106248kB, anon-rss:351544kB, file-rss:0kB, shmem-rss:2112kB, UID:1000 pgtables:3236kB oom_sc>
márc 31 16:49:45 surface pulseaudio[1449]: snd_pcm_dump():
márc 31 16:49:45 surface pulseaudio[1449]: Soft volume PCM
márc 31 16:49:45 surface pulseaudio[1449]: Control: PCM Playback Volume
márc 31 16:49:45 surface pulseaudio[1449]: min_dB: -51
márc 31 16:49:45 surface pulseaudio[1449]: max_dB: 0
márc 31 16:49:45 surface pulseaudio[1449]: resolution: 256
márc 31 16:49:45 surface pulseaudio[1449]: Its setup is:
márc 31 16:49:45 surface pulseaudio[1449]:   stream       : PLAYBACK
márc 31 16:49:45 surface pulseaudio[1449]:   access       : MMAP_INTERLEAVED
márc 31 16:49:45 surface pulseaudio[1449]:   format       : S16_LE
márc 31 16:49:45 surface pulseaudio[1449]:   subformat    : STD
márc 31 16:49:45 surface pulseaudio[1449]:   channels     : 2
márc 31 16:49:45 surface pulseaudio[1449]:   rate         : 48000
márc 31 16:49:45 surface pulseaudio[1449]:   exact rate   : 48000 (48000/1)
márc 31 16:49:45 surface pulseaudio[1449]:   msbits       : 16
márc 31 16:49:45 surface pulseaudio[1449]:   buffer_size  : 4408
márc 31 16:49:45 surface pulseaudio[1449]:   period_size  : 1102
márc 31 16:49:45 surface pulseaudio[1449]:   period_time  : 22958
márc 31 16:49:45 surface pulseaudio[1449]:   tstamp_mode  : ENABLE
márc 31 16:49:45 surface pulseaudio[1449]:   tstamp_type  : MONOTONIC
márc 31 16:49:45 surface pulseaudio[1449]:   period_step  : 1
márc 31 16:49:45 surface pulseaudio[1449]:   avail_min    : 1102
márc 31 16:49:45 surface pulseaudio[1449]:   period_event : 1
márc 31 16:49:45 surface pulseaudio[1449]:   start_threshold  : -1
márc 31 16:49:45 surface pulseaudio[1449]:   stop_threshold   : 4962966789362286592
márc 31 16:49:45 surface pulseaudio[1449]:   silence_threshold: 0
márc 31 16:49:45 surface pulseaudio[1449]:   silence_size : 0
márc 31 16:49:45 surface pulseaudio[1449]:   boundary     : 4962966789362286592
márc 31 16:49:45 surface pulseaudio[1449]: Slave: Hardware PCM card 0 'HDA Intel PCH' device 0 subdevice 0
márc 31 16:49:45 surface pulseaudio[1449]: Its setup is:
márc 31 16:49:45 surface pulseaudio[1449]:   stream       : PLAYBACK
márc 31 16:49:45 surface pulseaudio[1449]:   access       : MMAP_INTERLEAVED
márc 31 16:49:45 surface pulseaudio[1449]:   format       : S16_LE
márc 31 16:49:45 surface pulseaudio[1449]:   subformat    : STD
márc 31 16:49:45 surface pulseaudio[1449]:   channels     : 2
márc 31 16:49:45 surface pulseaudio[1449]:   rate         : 48000
márc 31 16:49:45 surface pulseaudio[1449]:   exact rate   : 48000 (48000/1)
márc 31 16:49:45 surface pulseaudio[1449]:   msbits       : 16
márc 31 16:49:45 surface pulseaudio[1449]:   buffer_size  : 4408
márc 31 16:49:45 surface pulseaudio[1449]:   period_size  : 1102
márc 31 16:49:45 surface pulseaudio[1449]:   period_time  : 22958
márc 31 16:49:45 surface pulseaudio[1449]:   tstamp_mode  : ENABLE
márc 31 16:49:45 surface pulseaudio[1449]:   tstamp_type  : MONOTONIC
márc 31 16:49:45 surface pulseaudio[1449]:   period_step  : 1
márc 31 16:49:45 surface pulseaudio[1449]:   avail_min    : 1102
márc 31 16:49:45 surface pulseaudio[1449]:   period_event : 1
márc 31 16:49:45 surface pulseaudio[1449]:   start_threshold  : -1
márc 31 16:49:45 surface pulseaudio[1449]:   stop_threshold   : 4962966789362286592
márc 31 16:49:45 surface pulseaudio[1449]:   silence_threshold: 0
márc 31 16:49:45 surface pulseaudio[1449]:   silence_size : 0
márc 31 16:49:45 surface pulseaudio[1449]:   boundary     : 4962966789362286592
márc 31 16:49:45 surface pulseaudio[1449]:   appl_ptr     : 1271811640
márc 31 16:49:45 surface pulseaudio[1449]:   hw_ptr       : 1271845784
márc 31 16:49:56 surface pulseaudio[1449]: snd_pcm_delay() returned a value that is exceptionally large: -93928 bytes (-489 ms).
márc 31 16:49:56 surface pulseaudio[1449]: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
márc 31 16:49:56 surface pulseaudio[1449]: snd_pcm_dump():
márc 31 16:49:56 surface pulseaudio[1449]: Soft volume PCM
márc 31 16:49:56 surface pulseaudio[1449]: Control: PCM Playback Volume
márc 31 16:49:56 surface pulseaudio[1449]: min_dB: -51
márc 31 16:49:56 surface pulseaudio[1449]: max_dB: 0
márc 31 16:49:56 surface pulseaudio[1449]: resolution: 256
márc 31 16:49:56 surface pulseaudio[1449]: Its setup is:
márc 31 16:49:56 surface pulseaudio[1449]:   stream       : PLAYBACK
márc 31 16:49:56 surface pulseaudio[1449]:   access       : MMAP_INTERLEAVED
márc 31 16:49:56 surface pulseaudio[1449]:   format       : S16_LE
márc 31 16:49:56 surface pulseaudio[1449]:   subformat    : STD
márc 31 16:49:56 surface pulseaudio[1449]:   channels     : 2
márc 31 16:49:56 surface pulseaudio[1449]:   rate         : 48000
márc 31 16:49:56 surface pulseaudio[1449]:   exact rate   : 48000 (48000/1)
márc 31 16:49:56 surface pulseaudio[1449]:   msbits       : 16
márc 31 16:49:56 surface pulseaudio[1449]:   buffer_size  : 4408
márc 31 16:49:56 surface pulseaudio[1449]:   period_size  : 1102
márc 31 16:49:56 surface pulseaudio[1449]:   period_time  : 22958
márc 31 16:49:56 surface pulseaudio[1449]:   tstamp_mode  : ENABLE
márc 31 16:49:56 surface pulseaudio[1449]:   tstamp_type  : MONOTONIC
márc 31 16:49:56 surface pulseaudio[1449]:   period_step  : 1
márc 31 16:49:56 surface pulseaudio[1449]:   avail_min    : 1102
márc 31 16:49:56 surface pulseaudio[1449]:   period_event : 1
márc 31 16:49:56 surface pulseaudio[1449]:   start_threshold  : -1
márc 31 16:49:56 surface pulseaudio[1449]:   stop_threshold   : 4962966789362286592
márc 31 16:49:56 surface pulseaudio[1449]:   silence_threshold: 0
márc 31 16:49:56 surface pulseaudio[1449]:   silence_size : 0
márc 31 16:49:56 surface pulseaudio[1449]:   boundary     : 4962966789362286592
márc 31 16:49:56 surface pulseaudio[1449]: Slave: Hardware PCM card 0 'HDA Intel PCH' device 0 subdevice 0
márc 31 16:49:56 surface pulseaudio[1449]: Its setup is:
márc 31 16:49:56 surface pulseaudio[1449]:   stream       : PLAYBACK
márc 31 16:49:56 surface pulseaudio[1449]:   access       : MMAP_INTERLEAVED
márc 31 16:49:56 surface pulseaudio[1449]:   format       : S16_LE
márc 31 16:49:56 surface pulseaudio[1449]:   subformat    : STD
márc 31 16:49:56 surface pulseaudio[1449]:   channels     : 2
márc 31 16:49:56 surface pulseaudio[1449]:   rate         : 48000
márc 31 16:49:56 surface pulseaudio[1449]:   exact rate   : 48000 (48000/1)
márc 31 16:49:56 surface pulseaudio[1449]:   msbits       : 16
márc 31 16:49:56 surface pulseaudio[1449]:   buffer_size  : 4408
márc 31 16:49:56 surface pulseaudio[1449]:   period_size  : 1102
márc 31 16:49:56 surface pulseaudio[1449]:   period_time  : 22958
márc 31 16:49:56 surface pulseaudio[1449]:   tstamp_mode  : ENABLE
márc 31 16:49:56 surface pulseaudio[1449]:   tstamp_type  : MONOTONIC
márc 31 16:49:56 surface pulseaudio[1449]:   period_step  : 1
márc 31 16:49:56 surface pulseaudio[1449]:   avail_min    : 1102
márc 31 16:49:56 surface pulseaudio[1449]:   period_event : 1
márc 31 16:49:56 surface pulseaudio[1449]:   start_threshold  : -1
márc 31 16:49:56 surface pulseaudio[1449]:   stop_threshold   : 4962966789362286592
márc 31 16:49:56 surface pulseaudio[1449]:   silence_threshold: 0
márc 31 16:49:56 surface pulseaudio[1449]:   silence_size : 0
márc 31 16:49:56 surface pulseaudio[1449]:   boundary     : 4962966789362286592
márc 31 16:49:56 surface pulseaudio[1449]:   appl_ptr     : 1272320744
márc 31 16:49:56 surface pulseaudio[1449]:   hw_ptr       : 1272344272

**Comment by perexg** [comment]
Dup of #68 . Do not report OOM (out-of-memory problems) to unrelated subsystems.
