### ISSUE TITLE
1.2.9: arithmetic exception in pcm/pcm_hw.c:753

### ISSUE THREAD

**Issue by engineeror** [alsa-project/alsa-lib#318]
[`period_size`](https://github.com/alsa-project/alsa-lib/blob/904f0f7e7a29244c05e5874bc36486638d1f7e7f/src/pcm/pcm_hw.c#LL753C33-L753C33  ) is zero on USB DACs: https://bugs.archlinux.org/index.php?do=details&task_id=78476

@perexg

**Comment by perexg** [comment]
I don't think it's correct to call drain on in uninitialized PCM stream:

https://github.com/DeaDBeeF-Player/deadbeef/blob/master/plugins/alsa/alsa.c

It's an application bug. But yes - the error code should be returned instead crash.
