### ISSUE TITLE
Alsa without support to usb headphone

### ISSUE THREAD

**Issue by wellinton-capixaba** [alsa-project/alsa-lib#326]
Hello. O recently built a media player (mplayer) with alsa support. However, telling mplayer to play multimedia files with alsa, specifying the usb headphone as the output device, didn't work.

However, latter I built another mplayer, this time using the system provided Also. Then I redid the test, and it worked as I originally expected.

The only difference I am aware between both also as is their version. The one I built it is the 1.0.17, while the system uses a 1.0.21.

Can be this the cause of the problem. Or is something else?

**Comment by perexg** [comment]
The report is very confusing and incomplete. Please, create only issues which can be resolved.
