### ISSUE TITLE
params argument to `SNDRV_PCM_IOCTL_SW_PARAMS` should be pointer

### ISSUE THREAD

**Issue by dancrossnyc** [alsa-project/alsa-lib#329]
Commit 2115cdb4d added a call to the `SNDRV_PCM_IOCTL_SW_PARAMS` ioctl on line 675 of src/pcm/pcm_hw.c, but passes the `sw_params` argument by value; this should be passed by pointer.

I ran across this in the context of the direwolf software modem for amateur radio; debugging details are in https://groups.io/g/direwolf/message/8286.

The patch is trivial; I will send a PR.

Thanks!

**Comment by perexg** [comment]
Thank you for this report.

**Comment by dancrossnyc** [comment]
Happy to do it; thank you for the quick turnaround!
