### ISSUE TITLE
Build is failing with python 3.8

### ISSUE THREAD

**Issue by seb128** [alsa-project/alsa-lib#33]
One build log from Ubuntu (1.1.9 but the current version has the same issue)
https://launchpadlibrarian.net/462093809/buildlog_ubuntu-focal-amd64.alsa-lib_1.1.9-0ubuntu4_BUILDING.txt.gz

The Ubuntu package has been fixed with that change
http://launchpadlibrarian.net/462101751/alsa-lib_1.2.1.2-2_1.2.1.2-2ubuntu1.diff.gz

The issue/needed changed is explained on https://docs.python.org/3/whatsnew/3.8.html

> To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.

The Ubuntu patch doesn't have that fallback logic though which is why I'm not proposing it with a merge request

**Comment by perexg** [comment]
The second commit is fine, I forgot to remove the original line in https://github.com/alsa-project/alsa-lib/commit/581a65ac9da06e9bada43ddad185125d0c4da497 .
