### ISSUE TITLE
alsa-utils-1.2.4's aplay play 11.025k wav file by digital Mi Headphone (S24_3LE) with abnormal electrical noise sound

### ISSUE THREAD

**Issue by raintiliang** [alsa-project/alsa-lib#338]
Hi, 
    we use  aplay play 11.025k wav file by digital Mi Headphone (S24_3LE) with abnormal electrical noise sound,  But aplay 8K, 16K, 32K,48K wav as normal except 11.025k, 22.05k, 44.1k.  May i have any idea ?

**Comment by perexg** [comment]
Use different rate plugin. The default is just linear resampling which is not so great (see `aplay -v ...` output).
