### ISSUE TITLE
Question: license compliance for libatopology 2.0.0

### ISSUE THREAD

**Issue by lucasgonze** [alsa-project/alsa-lib#343]
Given a binary linked with libatopology 2.0.0, and given that the LGPL requires source code to be bundled, it is unclear how to find the corresponding repo and tag (or release).

Thanks in advance for tips.

**Comment by mchehab** [comment]
Out of curiosity, as I never touched libatopology code, nor I'm a regular contributor to alsa-lib, but looking on its makefile (https://github.com/alsa-project/alsa-lib/blob/master/src/topology/Makefile.am) I can't see any binary linked there, only source files, and those are all there at the same dir. So, what binary are you referring to?

**Comment by lucasgonze** [comment]
Thanks for your comment, @mchehab. The binary is by a third party. They have a program that statically links libatopology.

**Comment by perexg** [comment]
There is snd_tplg_version() function which returns a static string. So you can dump the appropriate ELF section (objdump) to check the used version and it may be present in the statically linked program. But if not used, linker may strip it.

Something like:

```
$ objdump -sj .rodata libatopology.so.2.0.0 | colrm 1 44 | \
      tr -d '\n' | grep -o -E "1\\.[012]\\.[[:digit:]]+"
1.2.9
```

The topology code in alsa-lib follows LGPL 2.1.

What is your goal?

**Comment by lucasgonze** [comment]
Thanks for the tip, @perexg . My goal is to comply with the terms of the LGPL, which require source code to be made available. To do that I have to find the source.
