### ISSUE TITLE
Remove mic permissions.

### ISSUE THREAD

**Issue by stefan11111** [alsa-project/alsa-lib#353]
I first asked this on the gentoo forums: https://forums.gentoo.org/viewtopic-t-1164837.html
I would like to tweak my /dev/snd permissions in such a way that members of the audio group can listen to sounds, but only root and maybe root group can use the microphone to record sounds.
Is such a thing possible? Note that I have a static /dev, so no need to worry about changes not being permanent.

**Comment by perexg** [comment]
The capture (record) devices ends with `c` like `pcmC1D6c`. I guess you like to set the permissions for all.

**Comment by stefan11111** [comment]
Thanks, that worked.
Call it paranoia, but I want my mic to only work when I want it to work.
