### ISSUE TITLE
plug plugin bug and documentation error.

### ISSUE THREAD

**Issue by borine** [alsa-project/alsa-lib#372]
commit cd04da2 added the following text to the snd_pcm_poll_descriptors() documentation

> It is guaranteed that for the given PCM handle, the output poll
> descriptor structs (and their count) will never change, thus it is
> valid to call the function once and reuse its output for the
> lifetime of the PCM device.

I think that is not true. The `hw` pcm plugin has 1 poll descriptor just after opening, but enabling the `period_event` sw parameter changes this to 2 poll descriptors. And since the sw params can be changed at any time, so the poll
descriptor count can change at any time.

Also the ioplug plugin allows external io plugins to change the poll descriptor count at any arbitrary time, even without changes to `period_event`.

When looking at ths, I think I've found a bug in the `plug` plugin. That plugin sets `pcm->fast_ops = slave->fast_ops` when setting the hw params, but does not track changes to the hw fastops pointer (for example when enabling `period_event` with the `hw` plugin as slave of the plug).

**Comment by perexg** [comment]
Thanks, I overlooked this. I tried to address both issues.
