### ISSUE TITLE
Allow for an optional output in plugin multi

### ISSUE THREAD

**Issue by wonbinbk** [alsa-project/alsa-lib#379]
Let's say I have 2 sound cards, card 0 and card 1. Card 1 is unplug-able from the system so it might not exist when applications read asound.conf.

I think it makes sense to add ability to specify an optional pcm device which if it doesn't exist won't break alsa.

```
ALSA lib ../../alsa-lib-1.2.6.1/src/confmisc.c:165:(snd_config_get_card) Cannot get card index for 1
```

**Comment by perexg** [comment]
It's basically wrong to use multi plugin for cards with unsynchronized clocks.

I would suggest to use a sound server or more complex loopback (snd-aloop driver) / alsaloop combination (alsaloop may be restarted with different combinations on the hotplug event).
