### ISSUE TITLE
Linking failure when using separate builddir

### ISSUE THREAD

**Issue by jpalus** [alsa-project/alsa-lib#382]
If `$(builddir)` is different than `$(srcdir)` linking of `libatopology` fails:
```
$ mkdir builddir
$ cd builddir
$ ../configure
...
$ make
...
/usr/bin/ld: cannot open linker script file Versions: No such file or directory
```

`alsa-lib 1.2.11`

**Comment by ryandesign** [comment]
How could a release have been shipped with such a bug? Don't you test out-of-source builds?

Why hasn't there been a new release containing the fix?
