### ISSUE TITLE
Update CI to actions/checkout@v4

### ISSUE THREAD

**Issue by ryandesign** [alsa-project/alsa-lib#389]
As it says in the annotations of recent CI builds:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

In other words, switch to actions/checkout@v4.

**Comment by takaswie** [comment]
Hi @ryandesign,

Thanks for your indication. Indeed, the switch from v3 to v4 would suppress the github actions warnings.
Would you please make the merge request to solve the issue? I'm willing to review it.

Thanks
