### ISSUE TITLE
Unhandled asynchronous SIGIO

### ISSUE THREAD

**Issue by jansenmd** [alsa-project/alsa-lib#394]
When using `libasound.so` on embedded systems, I've come across several instances where an unhandled `SIGIO` is detected.  This can occur when closing a hardware microphone device that was set up to use asynchronous calls backs via `snd_async_add_pcm_handler`.

Example: when opening a hardware device with asynchronous callbacks:

* Sets up a signal handler for `SIGIO` via `sigaction`.
* Enable generation of signals from the `fd` by setting the `O_ASYNC` flag: `fcntl(fd, F_SETFL, flags | O_ASYNC)`
* Sets the signal to be generated: `fcntl(fd, F_SETSIG, (long)SIGIO)`

Now, when data is available to be read from the `fd`, `SIGIO` should be generated and handled by the signal handler set in `sigaction`.  That appears to work fine.

The current teardown process looks like this:

* Clear/reset the signal handler via `sigaction`.
* Disable generation of signals from the `fd` by clearing the `O_ASYNC` flag: `fcntl(fd, F_SETFL, flags & ~O_ASYNC)`
* Close the `fd`.

This teardown process seems to set up a race condition where an unhandled `SIGIO` can be generated between unregistering the signal handler and actually stopping any more signals from occurring.  Since the default action for `SIGIO` is termination, this can cause an application to unexpectedly terminate.

**Comment by perexg** [comment]
Thanks. The above commit should move `sigaction` after `fcntl`.

**Comment by velik76** [comment]
Hi all,

We are using alsa 1.2.12 with patch mentioned above, but have same behavior as reported by [jansenmd](https://github.com/jansenmd), via debugging we got that the part inside of:

`		switch (handler->type) {`

will be never called.

**Comment by perexg** [comment]
@velik76 : It's right. Could you test https://github.com/alsa-project/alsa-lib/commit/3b9f3b9431fe7adeca0bd3917f26a8877a1ee7e6 ?

**Comment by velik76** [comment]
@perexg: 

1. For last patch via some additional debug messages I can acknowledge, that code of snd_async_del_handler() now works as expected

2. Improvement idea for the snd_pcm_close(): it will be may be better to call the snd_pcm_drop() after the async handler deactivated. Because between snd_pcm_drop() and snd_async_del_handler() the signal could be generated that is sometimes could be not Ok

**Comment by perexg** [comment]
@velik76 : I made that change in https://github.com/alsa-project/alsa-lib/commit/93d7645d841d4e2c6a84c60b99a8392b8c511eb8 . But the async handler can be called before signal deactivation. It cannot be avoided and the application must handle this correctly in the async handler.
