### ISSUE TITLE
Ucm2 device sorting / ordering

### ISSUE THREAD

**Issue by beatboxa** [alsa-project/alsa-lib#397]
The sort order that devices are probed and ultimately listed in my OS sound settings is reversed--though consisten--from the order that they appear (top to bottom) in the UCM configuration files.  And they also do not appear consistent with configured device priority.

In other words, if the UCM configuration file hypothetically lists the following, from top to bottom:

1. Device 1 - priority 300
2. Device 2 - priority 100
3. Device 3 - priority 200

These devices will be probed and listed in the OS in the following order:

1. Device 3
2. Device 2
3. Device 1

I am currently creating a UCM config file for a device with 32 discreet output channels and 30 discreet input channels (and both stereo and mono device versions of many of these), so the sort order is crucial for user experience in a list this long.

Related:

- https://github.com/alsa-project/alsa-ucm-conf/pull/416#issuecomment-2111101525
- https://github.com/alsa-project/alsa-lib/issues/245#issuecomment-1168910073

**Comment by perexg** [comment]
It's not alsa-lib issue (see direct `alsaucm dump text` output), but a sound server issue (the user of UCM API). I already wrote this in  https://github.com/alsa-project/alsa-ucm-conf/pull/416#issuecomment-2111101525 .
