### ISSUE TITLE
alsa-project.org is down (2024)

### ISSUE THREAD

**Issue by xhamyd** [alsa-project/alsa-lib#398]
Noticed that our CI failed a bunch of jobs were unable to download https://www.alsa-project.org/files/pub/lib/alsa-lib-1.1.1.tar.bz2, starting at 2:08p PDT until now.

Is this a planned outage, or is there a plan to restore service? Thanks!

**Comment by perexg** [comment]
Thanks. The server is up again. The downtime culprit is being analyzed.
