### ISSUE TITLE
[Question] how to get underlying file descriptors

### ISSUE THREAD

**Issue by pfeatherstone** [alsa-project/alsa-lib#399]
I would like to use Alsa with the asio c++ library. I think all I need is the underlying file descriptor(s) for the device which I can then pass to Asio for polling and do all my asyncio. At the moment you're forced to use pollfd using snd_pcm_poll_descriptors(). Can I just read the fds or are there subtleties? Cheers

**Comment by takaswie** [comment]
> Can I just read the fds or are there subtleties?

Exactly. But note that the actual instance to which the underlying file descriptor refers is different depending on the type of PCM node; e.g. `hw` node would provide them for ALSA PCM character device and ALSA Timer character device, and `dmix` node would provide it just for ALSA Timer character device.

**Comment by pfeatherstone** [comment]
Ok thanks. Can you think of a way to hook ALSA into c++ ASIO library ?

**Comment by perexg** [comment]
https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html - see "Event waiting routines":

_The poll or select functions (see 'man 2 poll' or 'man 2 select' for further details) allows to receive requests/events from the device while an application is waiting on events from other sources (like keyboard, screen, network etc.), too. [snd_pcm_poll_descriptors](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga742e8705f6992fd0e36efc868e574f01) can be used to get file descriptors to poll or select on (note that wait direction might be different than expected - do not use only returned file descriptors, but handle events member as well - see [snd_pcm_poll_descriptors](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga742e8705f6992fd0e36efc868e574f01) function description for more details and [snd_pcm_poll_descriptors_revents](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga7e561f305702c6f52dab49b6c84f7df7) for events demangling). The implemented transfer routines can be found in the [ALSA transfers](https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html#alsa_transfers) section.__
