### ISSUE TITLE
Add persistent ID's for soundcards and midi devices (like coreaudio)

### ISSUE THREAD

**Issue by sjomae** [alsa-project/alsa-lib#407]
"This is something where macOS' Coreaudio/MIDI shines. Unlike macOS 
Linux/ALSA has no persistent unique IDs for soundcards or MIDI devices. 
ALSA supports hotplug, and first come first server sequential numeric 
IDs. The best you^Wpipewire can do is keep track of cards by name.

So this is not something pipewire can reliably address, until ALSA get 
support to identify cards by vendor and serial-number, and provide a UUID."

https://lists.linuxaudio.org/hyperkitty/list/linux-audio-dev@lists.linuxaudio.org/thread/OV63UFHRZ2LQYUDADZCUHC2MRA4JWPCU/

**Comment by perexg** [comment]
We have 'id' field for this purpose. It contains 15 ASCII characters and can be modified from the user space (e.g. udev rules or user). See `/proc/asound/cards` and the string between `[]`. Also, refer to:

```
cat /sys/class/sound/card0/id
echo "New_name" > /sys/class/sound/card0/id
```

So pipewire should use this string and not the card number for sound card identification.

**Comment by sjomae** [comment]
But does this also work for usb midi devices which are not soundcards? Like a launchpad midi controller for example.

**Comment by perexg** [comment]
If it's standard USB midi device, then ALSA creates "sound card" for those, too. Just look to `/proc/asound/cards`.

If controller is just USB HID (Human Interface Device), then another kernel driver handles them.
