### ISSUE TITLE
documentation incomplete for *avail_min, *avail_max

### ISSUE THREAD

**Issue by archenemies** [alsa-project/alsa-lib#44]
The following documentation is incomplete. It doesn't explain what "avail min" or "avail max" means. It's like asking someone you just met "what is your maximum age?". We need more context for the phrase "maximum number of frames available" to be meaningful. Is it maximum allowed before frames start getting dropped? Is it the maximum that we've seen over the course of operating the device?

https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___s_w___params.html

    snd_pcm_sw_params_get_avail_min()

        Get avail min from a software configuration container.

https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___status.html#gac58d13e4d03c9420c57428ddffd94964

    snd_pcm_status_get_avail_max()

        Get maximum number of frames available from a PCM status container after last
        snd_pcm_status call.

        Returns
            Maximum number of frames ready to be read/written

The following is less important, but it still should be fixed. We need to explain what a "software configuration container" is. The phrase is used all over the place; it only needs to be defined once:

https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga7e082d9ea701709270b0674a0be23b09

    snd_pcm_sw_params_t

    typedef struct _snd_pcm_sw_params snd_pcm_sw_params_t

    PCM software configuration container

**Comment by perexg** [comment]
The software container is explained here:

https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html

A pull request with the documentation refining is highly recommended.
