### ISSUE TITLE
Audios '.wav' simultaneos

### ISSUE THREAD

**Issue by CabralPro** [alsa-project/alsa-lib#45]
I would like to know how to play simultaneous audios because I am creating a piano with '.wav' files, and I cannot emit sounds simultaneously. I have this project ready in java, but I wanted to rewrite it in C ++ with alsa-lib. Thank you!

**Comment by perexg** [comment]
Use dmix plugin or another system to mix the different streams. But, it's probably easier to mix the samples directly in your app.
