### ISSUE TITLE
helem (MIXER,'Master Playback Volume',0,1,0) appears twice or more cannot load mixer controls: Invalid argument

### ISSUE THREAD

**Issue by igrekster** [alsa-project/alsa-lib#47]
I have a PCIE Asus Sound Card  (Asus Xonar AE) that uses USB interface:
```
Bus 003 Device 002: ID 0b05:180f ASUSTek Computer, Inc.
```
It's been working fine on earlier versions of  kernel/alsa-lib but at some point the volume control stopped working (the playback still works fine):

```
$ alsamixer -c 1
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.2-r1/work/alsa-lib-1.2.2/src/mixer/simple_none.c:1544:(simple_add1) helem (MIXER,'Master Playback Volume',0,1,0) appears twice or more
cannot load mixer controls: Invalid argument
```
This is on kernel 5.4.37/alsa 1.2.2. Unfortunately I cannot downgrade to the point when it was working to pinpoint the issue. I tried kernels 5.3.11 and alsa 1.1.8.
I've tried building the latest alsa-lib, and it is still showing the error.
I'm happy to try patches to alsa or kernel modules to help debug this.

```
$ amixer -c 1 controls
numid=7,iface=CARD,name='Clock Source 18 Validity'
numid=10,iface=CARD,name='Clock Source 19 Validity'
numid=17,iface=CARD,name='Clock Source 22 Validity'
numid=11,iface=CARD,name='IEC958 In - Output Jack'
numid=18,iface=CARD,name='Keep Interface'
numid=14,iface=CARD,name='Line - Input Jack'
numid=12,iface=CARD,name='Mic - Input Jack'
numid=8,iface=CARD,name='Speaker - Output Jack'
numid=20,iface=MIXER,name='Master Playback Volume'
numid=19,iface=MIXER,name='Master Playback Volume',device=1
numid=5,iface=MIXER,name='PCM Playback Switch'
numid=9,iface=MIXER,name='PCM Playback Switch',index=1
numid=16,iface=MIXER,name='PCM Capture Source'
numid=15,iface=MIXER,name='Line Capture Switch'
numid=13,iface=MIXER,name='Mic Capture Switch'
numid=6,iface=MIXER,name='Input Gain Pad Control'
numid=4,iface=PCM,name='Capture Channel Map'
numid=1,iface=PCM,name='Playback Channel Map'
numid=2,iface=PCM,name='Playback Channel Map',device=1
numid=3,iface=PCM,name='Playback Channel Map',device=2
```
`amixer -c scontrols` fails withe the same error as `alsamixer`.

A few more details:

[alsa-info.txt](https://github.com/alsa-project/alsa-lib/files/4569764/alsa-info.txt)
[proc-asound.txt](https://github.com/alsa-project/alsa-lib/files/4569766/proc-asound.txt)

**Comment by perexg** [comment]
It appears like a driver issue:

````
numid=20,iface=MIXER,name='Master Playback Volume'
numid=19,iface=MIXER,name='Master Playback Volume',device=1
````

The index field should be one not the device field. @tiwai ?

**Comment by igrekster** [comment]
I believe the second volume control is for the SPDIF optical output, which is a device in alsa lingo.

**Comment by tiwai** [comment]
> It appears like a driver issue:
> 
> ```
> numid=20,iface=MIXER,name='Master Playback Volume'
> numid=19,iface=MIXER,name='Master Playback Volume',device=1
> ```
> 
> The index field should be one not the device field. @tiwai ?

Those are user controls, so it's likely no kernel problem, but some applications created the controls wrongly.

Try to unload the all sound modules once, then remove your saved alsactl file (e.g. /var/lib/alsa/asound.state) and restart.

**Comment by igrekster** [comment]
@twai, I didn't think `asound.state` would impact it, but  it did. After removing the file I got it working, thank you.
