### ISSUE TITLE
Fix pour Asus Xonar U5 card SPIF in USB-Audio.conf

### ISSUE THREAD

**Issue by burningd0g** [alsa-project/alsa-lib#48]
It would be greatly apreciated to add the iec958 correct device in the default USB-Audio.conf for the Xonar USB sound card :

USB-Audio.pcm.iec958_device {
        ...
        "ASUS XONAR U5" 1
        "XONAR U5" 1
       ...
}

It would prevent me (and maybe some other people) to freak out on why it doesn't work out of the box! :)
I know the issue is also present on the U7 but i don't have all the possible device name for it.

Thanks!

**Comment by perexg** [comment]
Fixed in master.
