### ISSUE TITLE
Alsa doesn't respect XDG Base Directory standard?

### ISSUE THREAD

**Issue by rhysday** [alsa-project/alsa-lib#49]
My .config is set to $XDG_CONFIG_HOME and moving asoundrc to $XDG_CONFIG_HOME/alsa ...does not work for me.

**Comment by perexg** [comment]
alsa-lib is not a desktop library, it's system library.  You may use ALSA_CONFIG_DIR to override the /usr/share/alsa directory.

**Comment by tiwai** [comment]
Maybe we can add $XDG_CONFIG_HOME/asoundrc to the default search path in /usr/share/alsa/alsa.conf?

**Comment by luxintra** [comment]
Thanks! That did the trick. And yea it should be default. I changed the search path in /usr/share/alsa/alsa.conf to $XDG_CONFIG_HOME/alsa/asoundrc

**Comment by perexg** [comment]
Hmm, it seems that even git added the XDG_CONFIG_HOME support, so it's on my radar now.

We should load also ~/.config/alsa/asoundrc if XDG_CONFIG_HOME is not defined.

**Comment by perexg** [comment]
Commited to master.
