### ISSUE TITLE
5ee5ef31b5ff3fb7c904054cb9cac7478a727f7c breaks many unity games

### ISSUE THREAD

**Issue by escitalopram** [alsa-project/alsa-lib#52]
The games segfault right at the start. The actual crash happens with a backtrace that does not contain any libalsa functions.
Examples: I tried »Ara Fell« and »The Coma 2 Vicious Sisters« (sourced from gog.com), but there are probably more.

My gdb-fu is unfortunately not good enough to find out the exact problem. It would be very cool if this could be fixed on the libalsa-side, as many of those games will probably never see an update.

**Comment by perexg** [comment]
https://github.com/alsa-project/alsa-lib/issues/38
