### ISSUE TITLE
low volume libalsa 1.2.3

### ISSUE THREAD

**Issue by texstar** [alsa-project/alsa-lib#60]
Sound is about 30% lower with alsa 1.2.3 than with alsa 1.2.2 using the same volume setting. Backing down to 1.2.2 to restore order as the natives are getting stabby.

**Comment by perexg** [comment]
Provide some details, show `alsa-info.sh --no-upload` output for the normal / low volume behaviour.

**Comment by texstar** [comment]
fixed in 1.2.3.1
