### ISSUE TITLE
Realtek ALC892 produces low volume garbled output.

### ISSUE THREAD

**Issue by RoryO** [alsa-project/alsa-lib#69]
I'm sorry if this isn't the correct project for this. I don't know if this problem is relevant to the Alsa project or the Linux kernel directly and I don't know how to find that out.

Personal background
=== 

Programmer, experienced. First used Linux with Red Hat Linux 6 about 20 years ago. Mostly using Linux on the server side of things since. I'm not afraid to try things so have at it.

Problem
=== 

PCM audio to device heavily distorted and extremely low volume. Happens with all applications. Works flawlessly with Windows. Bypassing PulseAudio using aplay or speaker-test does not help. Interestingly, playing a raw sine wave with speaker-test works fine! Therefore it's only PCM based output causing an issue. Even using something like VLC which has it's own codecs and outputs directly to the sound buffer exhibits this issue, so it's not a system codec issue. For example, this produces a perfectly fine sounding sine wave

    speaker-test -l 3 -t sine -c 2

And this produces nothing

    speaker-test -l 3 -t wav -c 2

If I play something on Spotify or Youtube and max out the volume I can barely hear some heavily distorted, clipped noise vaguely sounding like it should.

I only have powered headphones for testing, no powered external speakers.

Relevant details
===

Latest KDE neon, which is Ubuntu 18.04 base with the GUI switched from Gnome to KDE Plasma.

Hardware is an Asus z170 motherboard, integrated Realtek/Intel audio. Using the rear green line out jack. I think there are headphone jack headers on the board as well, they are unused.

lspci output

    00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31)
    01:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)

kernel messages regarding snd

    snd_hda_intel 0000:01:00.1: Disabling MSI
    snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
    snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC892: line_outs=3 (0x14/0x15/0x16/0x0/0x0) type:line
    snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
    snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x1b/0x0/0x0/0x0/0x0)
    snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
    snd_hda_codec_realtek hdaudioC0D0:    dig-out=0x11/0x1e
    snd_hda_codec_realtek hdaudioC0D0:    inputs:
    snd_hda_codec_realtek hdaudioC0D0:      Front Mic=0x19
    snd_hda_codec_realtek hdaudioC0D0:      Rear Mic=0x18
    snd_hda_codec_realtek hdaudioC0D0:      Line=0x1a

Output of alsa-info dumping everything it knows about

https://pastebin.com/wCif6Qzv

I'm stuck and don't know where to go from here. Since utilities like aplay and sound-test bypass PulseAudio I think it's a problem with Alsa or the device driver for this card. That's as far as I can discover on my own.

Things I have tried
===

- Using alsamixer, confirming all volume sliders at max, none are muted. Maxing out all sliders is when I can barely make out garbled output through powered headphones.
- Using Ubuntu Mainline Kernel Installer, signing it properly, and upgrading the kernel from 5.3.0 to 5.7.9
- Using `hdajackretask` and overriding jack plugin detection
- Modifying PulseAudio config to not resample and force sampling to 44.1khz
- Playing around with `pavucontrol` and kde equivalents, disabling the unused nvidia output and trying different jack configurations 

I also found some modprobe settings for Realtek devices, however usually that information was usually about 6-8 years old and didn't look relevant.

**Comment by perexg** [comment]
Apparently, it's a kernel driver bug. Please, report it to https://bugzilla.kernel.org .
