### ISSUE TITLE
Is period_size bytes per period or frames per period?

### ISSUE THREAD

**Issue by crocket** [alsa-project/alsa-lib#8]
According to https://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html
period_size in dmix is bytes per period.

According to aplay --dump-hw-params -D dmix ...
period_size is frames per period.

Which one is right?

**Comment by cladisch** [comment]
The plugins page is wrong (for dmix/dshare/dsnoop); the period size is always measured in frames.

**Comment by crocket** [comment]
I think the documentation should fix the errors.

**Comment by perexg** [comment]
Fixed in 7a345a5c20107e1db06252f527e795c060ce98af . Thanks for the report.
