### ISSUE TITLE
Is raw MIDI API  really raw ? (Running status)

### ISSUE THREAD

**Issue by MusicMaker** [alsa-project/alsa-lib#80]
A device is sending always 3 bytes for note off/on event. The host application uses a virtual port to receive the data  The ALSA RAW MIDI API seems to remove the status byte if the channel of the status byte is the same. Once the channel changes, the RAW MIDI API provide the status byte to the higher level layer. Is this the bahaviour of the RAW MIDI API ? if yes then raw isn't actually raw. Can this  be disabled ? Could not find a parameter at port open to do this. (not using the sequencer)

**Comment by keinstein** [comment]
Is your JACK server using the RAW MIDI interface or does it connect to the ALSA sequencer API? In the latter case you have the scheme RAW Software ⇒ ALSA Sequencer ⇒ JACK ⇒ ALSA Sequencer ⇒ RAW Device . So the inner part is not RAW and Running status is normalised according whatever is configured in the conversion from ALSA to RAW.

**Comment by perexg** [comment]
Answered.
