### ISSUE TITLE
 unable to initialize sum ring buffer error

### ISSUE THREAD

**Issue by Komal1809** [alsa-project/alsa-lib#83]
i am using alsa-lib-1.1.4.1 library version. Whenever trying to play audio from file using aplay  getting error as alsa-lib-1.1.4.1/src/pcm/pcm_dmix.c:1177: **(snd_pcm_dmix_open) unable to initialize sum ring buffer** 

Note : audio is getting played at the start once system reboot
Please let me know how to debug this issue

**Comment by perexg** [comment]
The dmix code uses System V shared memory (man 2 shmget). You may check, if permissions are ok.

**Comment by perexg** [comment]
Stalled. Closing.
