### ISSUE TITLE
error(no sound) over boundary time [src/pcm/pcm_dshare.c]

### ISSUE THREAD

**Issue by syuuha** [alsa-project/alsa-lib#84]
there is an issue when we use pcm_dshare over boundary time,
eg.  will be no sound after 12 hours 

[src/pcm/pcm_dshare.c] Line 114:

[before]
	/* calculate the size to transfer */
	size = dshare->appl_ptr - dshare->last_appl_ptr;

[after]
	/* calculate the size to transfer */
	if (dshare->appl_ptr < dshare->last_appl_ptr)
		size = dshare->appl_ptr + (pcm->boundary - dshare->last_appl_ptr);
	else
		size = dshare->appl_ptr - dshare->last_appl_ptr;

**Comment by perexg** [comment]
Thanks. Fixed in ebe2f8b85132757fa8deb3a8e511d5cc06c53c8d (and 6d06fcc285babd19afba3d3c14206f17e1b2583b cleanup).
