### ISSUE TITLE
DOC or BUG: plugins dsnoop, dmix and dshare change mode parameter of  snd_pcm_open_slave

### ISSUE THREAD

**Issue by RonaldAJ** [alsa-project/alsa-lib#92]
Using the dsnoop plugin sets the mode to non-blocking in alsa-lib/src/pcm/pcm_dsnoop.c:

    ret = snd_pcm_open_slave(&spcm, root, sconf, stream,
                             mode | SND_PCM_NONBLOCK |
                             SND_PCM_APPEND,
                             NULL);
Judging from the code the same applies for dmix, dshare. 

It took me a considerable amount of time to figure this out using the source code. So it would be nice if this behaviour where documented.

Personally I would prefer the code to throw an error message, when using blocking mode with these plugins. But I don't know how that ties in with the overall design.

**Comment by perexg** [comment]
What problem do you have in your application? It's internal settings, you should not see it in the app.

**Comment by RonaldAJ** [comment]
I was expecting to get the number specified by the size parameter, because I specified mode=alsaaudio.PCM_NORMAL when opening my device using pyalsaaudio. This implies that from pyalsaaudio the alsa method snd_pcm_open is called with mode = 0, which should give blocking access to the microphone.

But the code indicated in the post above overrides this. And I guess for good reasons. But it leads to unexpected behavior, for if I work with the plughw device I get the number of samples specified ( 4410 ), but if I switch to dsnoop for the same microphone I get fewer samples then asked for (940). 

I would have preferred it if snd_pcm_open had returned an informative error.

**Comment by perexg** [comment]
The slave pcm mode is not relevant. The dsnoop (direct) plugins maintain own ring buffer pointers and the mmap functions should be used internally like snd_pcm_mmap_readi() -> snd_pcm_read_areas(). The second function have code to block the read operation until the conditions are fulfilled. You should check this function why it breaks early for dsnoop.

**Comment by RonaldAJ** [comment]
Well then the internal ringbuffers don't respond to the size set. The behaviour is clear.

**Comment by perexg** [comment]
The size argument is from the application and should be propagated to all described functions. You may debug things or show a minimal test code to reproduce your behaviour.

**Comment by RonaldAJ** [comment]
The size is derived from a slave it seems: 
`diff = pcm_frame_diff(slave_hw_ptr, old_slave_hw_ptr, dsnoop->slave_boundary);`
But that is guessing based on the parameter names.

pcm_dsnoop.c close to line 155

Where diff is the size passed later to  `snd_pcm_dsnoop_sync_area`.

I'll work on a minimal example, but using pyalsaaudio.

**Comment by perexg** [comment]
I'm afraid. You mix internals with the external API. The snd_pcm_dsnoop_sync_ptr() is not relevant for the API read operation.

**Comment by RonaldAJ** [comment]
Well I am in the dark. I guess I better spend time on the minimal example than learning the internals of ALSA.  

Thanks sofar! I need a bit of time to make a good minimal example.

**Comment by RonaldAJ** [comment]
Here is a version of recordtest.py from pyalsaaudio with minor modifications:

```python
#!/usr/bin/env python3
# -*- mode: python; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-

## recordtest.py
##
## This is an example of a simple sound capture script.
##
## The script opens an ALSA pcm device for sound capture, sets
## various attributes of the capture, and reads in a loop,
## writing the data to standard out.
##
## To test it out do the following:
## python recordtest.py out.raw # talk to the microphone
## aplay -r 8000 -f S16_LE -c 1 out.raw

#!/usr/bin/env python

import sys
import time
import getopt
import alsaaudio
import struct

def usage():
    print('usage: recordtest.py [-d <device>] <file>', file=sys.stderr)
    sys.exit(2)

if __name__ == '__main__':

    device = 'default'

    opts, args = getopt.getopt(sys.argv[1:], 'd:')
    for o, a in opts:
        if o == '-d':
            device = a

    print(f'device is {device}')
    
    # print(f' devices: \n {alsaaudio.pcms()}')
    if not args:
        usage()

    f = open(args[0], 'wb')

    # Open the device in nonblocking capture mode in mono, with a sampling rate of 44100 Hz 
    # and 16 bit little endian samples
    # The period size controls the internal number of frames per period.
    # The significance of this parameter is documented in the ALSA api.
    # For our purposes, it is suficcient to know that reads from the device
    # will return this many frames. Each frame being 2 bytes long.
    # This means that the reads below will return either 320 bytes of data
    # or 0 bytes of data. The latter is possible because we are in nonblocking
    # mode.
    rate= 44100
    periodsize=4000
    
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, 
        channels=1, rate=rate, format=alsaaudio.PCM_FORMAT_S16_LE,
        periodsize=periodsize, device=device)


    print(f'device card: {inp.cardname()} \n')
    loops = 10
    while loops > 0:
        loops -= 1
        # Read data from device
        noofsamples, data = inp.read()
        print(f'noofsamples: {noofsamples}')


        noofbytes = 2* noofsamples  # 2 is for 16 bit formats
        if noofbytes > 0 :
            print(f'data snippet: {data[noofbytes-10:noofbytes]}')
            if noofbytes+10 < periodsize:
                print(f'data snippet : {data[noofbytes:-2*periodsize+noofbytes+10]} \n\n')
            
            npdata = struct.unpack("<" + "h"*noofsamples, data[:noofbytes])
            #print(npdata[:10])
            f.write(data[:noofbytes])
            
        elif noofbytes < 0:
            print('buffer overrrun')
```

First pyalsaaudio needs to be installed as a python module: http://larsimmisch.github.io/pyalsaaudio/pyalsaaudio.html#installation

Call with different plugins:
```bash
python recordtest.py -d plughw test.raw
```

Call with different plugins:
```bash
python recordtest.py -d dsnoop test.raw
```

Output on my VM:



```bash
(gui) ronald@SA:pyalsaaudio$ python recordtest.py -d dsnoop test.raw
device is dsnoop
device card: dsnoop 

noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data snippet : b'' 


noofsamples: 1024
data snippet: b')\xf8\xa3\xfd\xd9\xf7,\xfd\x00\xf8'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\xc9\x0e\xdc\xfe\x0c\x0b\x06\xff\x18\x08'
data snippet : b'' 


noofsamples: 1024
data snippet: b'\xd3\xfen\xf6[\xfe\xb8\xf4\xbd\xfd'
data snippet : b'' 


(gui) ronald@SA:pyalsaaudio$ python recordtest.py -d plughw test.raw
device is plughw
device card: plughw 

noofsamples: 4000
data snippet: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
noofsamples: 4000
data snippet: b'\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00'
noofsamples: 4000
data snippet: b'\xff\xff\x00\x00\x00\x00\x00\x00\xff\xff'
noofsamples: 4000
data snippet: b'\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00'
noofsamples: 4000
data snippet: b'\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00'
noofsamples: 4000
data snippet: b'\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00'
noofsamples: 4000
data snippet: b'\xfd\xff\xfc\xff\xfc\xff\xfc\xff\xfc\xff'
noofsamples: 4000
data snippet: b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
noofsamples: 4000
data snippet: b'\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00'
noofsamples: 4000
data snippet: b'\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00'
(gui) ronald@SA:pyalsaaudio$ 
```

**Comment by RonaldAJ** [comment]
Notes: 
- For pyalsaaudio I proposed a workaround for a potentially related issue: https://github.com/larsimmisch/pyalsaaudio/pull/91
- There is fair chance also pyaudio/portaudio is affected. Reason for using pyalsaaudio were inexplicable problems  with recording using Raspian buster on RPi 4. The arecord commandline tool works in those situations, but when using pyaudio it is all noise.

**Comment by perexg** [comment]
It's all correct. The direct plugins restraint the buffer parameters differently, so you cannot  expect that the period size and buffer size will be **exact** as you requested.

<pre>
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, 
        channels=1, rate=rate, format=alsaaudio.PCM_FORMAT_S16_LE,
        periodsize=periodsize, device=device)
    inp.dumpinfo()
</pre>

Result (for dsnoop):

<pre>
period size = 1024 frames
buffer size = 4096 frames
</pre>

So the snd_pcm_readi() behaves correctly. You may force different period/buffer size parameters using the configuration option - see https://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html (look for dsnoop).

Example (to ~/.asoundrc or /etc/alsa/conf.d or so:

<pre>
pcm.my_dsnoop {
  type dsnoop
  ipc_key 1000
  ipc_perm 0600
  slave.period_size 4000
  slave.buffer_size 16000
  slave.pcm "hw:0,0"
}
</pre>

Another way is to use the global values:

<pre>
cards./CARD_DRIVER/.pcm.dsnoop.period_size 4000
cards./CARD_DRIVER/.pcm.dsnoop.periods 4
</pre>

Replace /CARD_DRIVER/ with the driver name. It's the first string after ]: in /proc/asound/cards like:

<pre>
$ cat /proc/asound/cards 
 0 [Headset        ]: USB-Audio - Logitech USB Headset
                      Logitech Logitech USB Headset at usb-0000:09:00.0-2.1.3, full speed
</pre>

The /CARD_DRIVER/ is *USB-Audio* string here.

**Comment by RonaldAJ** [comment]
Thanks! I guess that contains the solution. I will need to play around with that a bit.

**Comment by RonaldAJ** [comment]
I am writing a function for pyalsaaudio now, that will return the dumpinfo data as a dictionary (see below for example output). I can then implement a check on whether the device realized has the parameters as I requested them. If not then I can throw an exception and take action on the ALSA side. Following the ideas suggested above.

I can't find access to what pyalsaaudio code calls the mode (using for example SND_PCM_NONBLOCK) and type (using for example SND_PCM_STREAM_CAPTURE) parameters. I have been digging in the alsa code and documentation, but I have the impression that by design I cannot retrieve these flags and I can only set them (using for example snd_pcm_nonblock for the mode) .  

Hence my question: is it possible to read mode and type from the pcm device using existing alsa-lib functions? 


-------------------------------------------------------------------------------------------------------------------------------------------------------
Current output of the info function formatted as json, with the fields of interest marked with (call value):
        {
            " (call value) mode": 0,
            " (call value) mode_name": "PCM_NORMAL",
            " (call value) type": 1,
            " (call value) type_name": "CAPTURE",
            "access_type": "RW_INTERLEAVED",
            "buffer_size": 4096,
            "buffer_time": 0,
            "can_mmap_sample_resolution": false,
            "can_overrange": false,
            "can_pause": false,
            "can_resume": false,
            "can_sync_start": false,
            "channels": 1,
            "format": 2,
            "format_description": "Signed 16 bit Little Endian",
            "format_name": "S16_LE",
            "get_periods": 0,
            "is_batch": true,
            "is_block_transfer": true,
            "is_double": false,
            "is_half_duplex": false,
            "is_joint_duplex": false,
            "name": "plugsnoop:CARD=GoMic,DEV=0",
            "period_size": 1024,
            "period_time": 21333,
            "rate": 48000,
            "rate_numden": [
                48000,
                1
            ],
            "significant_bits": 16,
            "state": "PREPARED",
            "subformat_description": "Standard",
            "subformat_name": "STD"
        }

**Comment by perexg** [comment]
> I can't find access to what pyalsaaudio code calls the mode (using for example SND_PCM_NONBLOCK) and type (using for example SND_PCM_STREAM_CAPTURE) parameters. I have been digging in the alsa code and documentation, but I have the impression that by design I cannot retrieve these flags and I can only set them (using for example snd_pcm_nonblock for the mode) .

The caller should trace this settings.

**Comment by RonaldAJ** [comment]
Thanks! That confirms my analysis.
